# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: translation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='translation.proto',
  package='nanoem.translation',
  syntax='proto2',
  serialized_pb=_b('\n\x11translation.proto\x12\x12nanoem.translation\"\"\n\x06Phrase\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04text\x18\x02 \x02(\t\"c\n\x04Unit\x12.\n\x08language\x18\x01 \x02(\x0e\x32\x1c.nanoem.translation.Language\x12+\n\x07phrases\x18\x02 \x03(\x0b\x32\x1a.nanoem.translation.Phrase\"1\n\x06\x42undle\x12\'\n\x05units\x18\x01 \x03(\x0b\x32\x18.nanoem.translation.Unit*+\n\x08Language\x12\x0f\n\x0bLC_JAPANESE\x10\x01\x12\x0e\n\nLC_ENGLISH\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_LANGUAGE = _descriptor.EnumDescriptor(
  name='Language',
  full_name='nanoem.translation.Language',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LC_JAPANESE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LC_ENGLISH', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LC_SIMPLIFIED_CHINESE', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LC_TRADITIONAL_CHINESE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=229,
  serialized_end=272,
)
_sym_db.RegisterEnumDescriptor(_LANGUAGE)

Language = enum_type_wrapper.EnumTypeWrapper(_LANGUAGE)
LC_JAPANESE = 1
LC_ENGLISH = 2
LC_SIMPLIFIED_CHINESE = 3
LC_TRADITIONAL_CHINESE = 4



_PHRASE = _descriptor.Descriptor(
  name='Phrase',
  full_name='nanoem.translation.Phrase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nanoem.translation.Phrase.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='nanoem.translation.Phrase.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='nanoem.translation.Phrase.text', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='nanoem.translation.Phrase.text', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=75,
)


_UNIT = _descriptor.Descriptor(
  name='Unit',
  full_name='nanoem.translation.Unit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='nanoem.translation.Unit.language', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phrases', full_name='nanoem.translation.Unit.phrases', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language', full_name='nanoem.translation.Unit.language', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language', full_name='nanoem.translation.Unit.language', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=176,
)


_BUNDLE = _descriptor.Descriptor(
  name='Bundle',
  full_name='nanoem.translation.Bundle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='nanoem.translation.Bundle.units', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=227,
)

_UNIT.fields_by_name['language'].enum_type = _LANGUAGE
_UNIT.fields_by_name['phrases'].message_type = _PHRASE
_BUNDLE.fields_by_name['units'].message_type = _UNIT
DESCRIPTOR.message_types_by_name['Phrase'] = _PHRASE
DESCRIPTOR.message_types_by_name['Unit'] = _UNIT
DESCRIPTOR.message_types_by_name['Bundle'] = _BUNDLE
DESCRIPTOR.enum_types_by_name['Language'] = _LANGUAGE

Phrase = _reflection.GeneratedProtocolMessageType('Phrase', (_message.Message,), dict(
  DESCRIPTOR = _PHRASE,
  __module__ = 'translation_pb2'
  # @@protoc_insertion_point(class_scope:nanoem.translation.Phrase)
  ))
_sym_db.RegisterMessage(Phrase)

Unit = _reflection.GeneratedProtocolMessageType('Unit', (_message.Message,), dict(
  DESCRIPTOR = _UNIT,
  __module__ = 'translation_pb2'
  # @@protoc_insertion_point(class_scope:nanoem.translation.Unit)
  ))
_sym_db.RegisterMessage(Unit)

Bundle = _reflection.GeneratedProtocolMessageType('Bundle', (_message.Message,), dict(
  DESCRIPTOR = _BUNDLE,
  __module__ = 'translation_pb2'
  # @@protoc_insertion_point(class_scope:nanoem.translation.Bundle)
  ))
_sym_db.RegisterMessage(Bundle)


# @@protoc_insertion_point(module_scope)
