/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "common.pb-c.h"
void   nanoem__common__annotation__init
                     (Nanoem__Common__Annotation         *message)
{
  static const Nanoem__Common__Annotation init_value = NANOEM__COMMON__ANNOTATION__INIT;
  *message = init_value;
}
size_t nanoem__common__annotation__get_packed_size
                     (const Nanoem__Common__Annotation *message)
{
  assert(message->base.descriptor == &nanoem__common__annotation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__annotation__pack
                     (const Nanoem__Common__Annotation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__annotation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__annotation__pack_to_buffer
                     (const Nanoem__Common__Annotation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__annotation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Annotation *
       nanoem__common__annotation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Annotation *)
     protobuf_c_message_unpack (&nanoem__common__annotation__descriptor,
                                allocator, len, data);
}
void   nanoem__common__annotation__free_unpacked
                     (Nanoem__Common__Annotation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__annotation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__vector3__init
                     (Nanoem__Common__Vector3         *message)
{
  static const Nanoem__Common__Vector3 init_value = NANOEM__COMMON__VECTOR3__INIT;
  *message = init_value;
}
size_t nanoem__common__vector3__get_packed_size
                     (const Nanoem__Common__Vector3 *message)
{
  assert(message->base.descriptor == &nanoem__common__vector3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__vector3__pack
                     (const Nanoem__Common__Vector3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__vector3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__vector3__pack_to_buffer
                     (const Nanoem__Common__Vector3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__vector3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Vector3 *
       nanoem__common__vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Vector3 *)
     protobuf_c_message_unpack (&nanoem__common__vector3__descriptor,
                                allocator, len, data);
}
void   nanoem__common__vector3__free_unpacked
                     (Nanoem__Common__Vector3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__vector3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__vector4__init
                     (Nanoem__Common__Vector4         *message)
{
  static const Nanoem__Common__Vector4 init_value = NANOEM__COMMON__VECTOR4__INIT;
  *message = init_value;
}
size_t nanoem__common__vector4__get_packed_size
                     (const Nanoem__Common__Vector4 *message)
{
  assert(message->base.descriptor == &nanoem__common__vector4__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__vector4__pack
                     (const Nanoem__Common__Vector4 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__vector4__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__vector4__pack_to_buffer
                     (const Nanoem__Common__Vector4 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__vector4__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Vector4 *
       nanoem__common__vector4__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Vector4 *)
     protobuf_c_message_unpack (&nanoem__common__vector4__descriptor,
                                allocator, len, data);
}
void   nanoem__common__vector4__free_unpacked
                     (Nanoem__Common__Vector4 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__vector4__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__color__init
                     (Nanoem__Common__Color         *message)
{
  static const Nanoem__Common__Color init_value = NANOEM__COMMON__COLOR__INIT;
  *message = init_value;
}
size_t nanoem__common__color__get_packed_size
                     (const Nanoem__Common__Color *message)
{
  assert(message->base.descriptor == &nanoem__common__color__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__color__pack
                     (const Nanoem__Common__Color *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__color__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__color__pack_to_buffer
                     (const Nanoem__Common__Color *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__color__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Color *
       nanoem__common__color__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Color *)
     protobuf_c_message_unpack (&nanoem__common__color__descriptor,
                                allocator, len, data);
}
void   nanoem__common__color__free_unpacked
                     (Nanoem__Common__Color *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__color__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__quaternion__init
                     (Nanoem__Common__Quaternion         *message)
{
  static const Nanoem__Common__Quaternion init_value = NANOEM__COMMON__QUATERNION__INIT;
  *message = init_value;
}
size_t nanoem__common__quaternion__get_packed_size
                     (const Nanoem__Common__Quaternion *message)
{
  assert(message->base.descriptor == &nanoem__common__quaternion__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__quaternion__pack
                     (const Nanoem__Common__Quaternion *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__quaternion__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__quaternion__pack_to_buffer
                     (const Nanoem__Common__Quaternion *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__quaternion__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Quaternion *
       nanoem__common__quaternion__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Quaternion *)
     protobuf_c_message_unpack (&nanoem__common__quaternion__descriptor,
                                allocator, len, data);
}
void   nanoem__common__quaternion__free_unpacked
                     (Nanoem__Common__Quaternion *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__quaternion__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__interpolation__init
                     (Nanoem__Common__Interpolation         *message)
{
  static const Nanoem__Common__Interpolation init_value = NANOEM__COMMON__INTERPOLATION__INIT;
  *message = init_value;
}
size_t nanoem__common__interpolation__get_packed_size
                     (const Nanoem__Common__Interpolation *message)
{
  assert(message->base.descriptor == &nanoem__common__interpolation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__interpolation__pack
                     (const Nanoem__Common__Interpolation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__interpolation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__interpolation__pack_to_buffer
                     (const Nanoem__Common__Interpolation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__interpolation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Interpolation *
       nanoem__common__interpolation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Interpolation *)
     protobuf_c_message_unpack (&nanoem__common__interpolation__descriptor,
                                allocator, len, data);
}
void   nanoem__common__interpolation__free_unpacked
                     (Nanoem__Common__Interpolation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__interpolation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__point__init
                     (Nanoem__Common__Point         *message)
{
  static const Nanoem__Common__Point init_value = NANOEM__COMMON__POINT__INIT;
  *message = init_value;
}
size_t nanoem__common__point__get_packed_size
                     (const Nanoem__Common__Point *message)
{
  assert(message->base.descriptor == &nanoem__common__point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__point__pack
                     (const Nanoem__Common__Point *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__point__pack_to_buffer
                     (const Nanoem__Common__Point *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Point *
       nanoem__common__point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Point *)
     protobuf_c_message_unpack (&nanoem__common__point__descriptor,
                                allocator, len, data);
}
void   nanoem__common__point__free_unpacked
                     (Nanoem__Common__Point *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__size__init
                     (Nanoem__Common__Size         *message)
{
  static const Nanoem__Common__Size init_value = NANOEM__COMMON__SIZE__INIT;
  *message = init_value;
}
size_t nanoem__common__size__get_packed_size
                     (const Nanoem__Common__Size *message)
{
  assert(message->base.descriptor == &nanoem__common__size__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__size__pack
                     (const Nanoem__Common__Size *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__size__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__size__pack_to_buffer
                     (const Nanoem__Common__Size *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__size__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Size *
       nanoem__common__size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Size *)
     protobuf_c_message_unpack (&nanoem__common__size__descriptor,
                                allocator, len, data);
}
void   nanoem__common__size__free_unpacked
                     (Nanoem__Common__Size *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__size__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__rect__init
                     (Nanoem__Common__Rect         *message)
{
  static const Nanoem__Common__Rect init_value = NANOEM__COMMON__RECT__INIT;
  *message = init_value;
}
size_t nanoem__common__rect__get_packed_size
                     (const Nanoem__Common__Rect *message)
{
  assert(message->base.descriptor == &nanoem__common__rect__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__rect__pack
                     (const Nanoem__Common__Rect *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__rect__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__rect__pack_to_buffer
                     (const Nanoem__Common__Rect *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__rect__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Rect *
       nanoem__common__rect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Rect *)
     protobuf_c_message_unpack (&nanoem__common__rect__descriptor,
                                allocator, len, data);
}
void   nanoem__common__rect__free_unpacked
                     (Nanoem__Common__Rect *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__rect__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nanoem__common__rational__init
                     (Nanoem__Common__Rational         *message)
{
  static const Nanoem__Common__Rational init_value = NANOEM__COMMON__RATIONAL__INIT;
  *message = init_value;
}
size_t nanoem__common__rational__get_packed_size
                     (const Nanoem__Common__Rational *message)
{
  assert(message->base.descriptor == &nanoem__common__rational__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nanoem__common__rational__pack
                     (const Nanoem__Common__Rational *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nanoem__common__rational__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nanoem__common__rational__pack_to_buffer
                     (const Nanoem__Common__Rational *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nanoem__common__rational__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nanoem__Common__Rational *
       nanoem__common__rational__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nanoem__Common__Rational *)
     protobuf_c_message_unpack (&nanoem__common__rational__descriptor,
                                allocator, len, data);
}
void   nanoem__common__rational__free_unpacked
                     (Nanoem__Common__Rational *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nanoem__common__rational__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nanoem__common__annotation__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Annotation, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Annotation, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__annotation__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange nanoem__common__annotation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nanoem__common__annotation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Annotation",
  "Annotation",
  "Nanoem__Common__Annotation",
  "nanoem.common",
  sizeof(Nanoem__Common__Annotation),
  2,
  nanoem__common__annotation__field_descriptors,
  nanoem__common__annotation__field_indices_by_name,
  1,  nanoem__common__annotation__number_ranges,
  (ProtobufCMessageInit) nanoem__common__annotation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__vector3__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector3, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector3, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector3, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__vector3__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange nanoem__common__vector3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nanoem__common__vector3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Vector3",
  "Vector3",
  "Nanoem__Common__Vector3",
  "nanoem.common",
  sizeof(Nanoem__Common__Vector3),
  3,
  nanoem__common__vector3__field_descriptors,
  nanoem__common__vector3__field_indices_by_name,
  1,  nanoem__common__vector3__number_ranges,
  (ProtobufCMessageInit) nanoem__common__vector3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__vector4__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector4, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector4, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector4, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Vector4, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__vector4__field_indices_by_name[] = {
  3,   /* field[3] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange nanoem__common__vector4__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nanoem__common__vector4__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Vector4",
  "Vector4",
  "Nanoem__Common__Vector4",
  "nanoem.common",
  sizeof(Nanoem__Common__Vector4),
  4,
  nanoem__common__vector4__field_descriptors,
  nanoem__common__vector4__field_indices_by_name,
  1,  nanoem__common__vector4__number_ranges,
  (ProtobufCMessageInit) nanoem__common__vector4__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__color__field_descriptors[4] =
{
  {
    "red",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Color, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Color, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Color, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alpha",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Color, alpha),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__color__field_indices_by_name[] = {
  3,   /* field[3] = alpha */
  2,   /* field[2] = blue */
  1,   /* field[1] = green */
  0,   /* field[0] = red */
};
static const ProtobufCIntRange nanoem__common__color__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nanoem__common__color__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Color",
  "Color",
  "Nanoem__Common__Color",
  "nanoem.common",
  sizeof(Nanoem__Common__Color),
  4,
  nanoem__common__color__field_descriptors,
  nanoem__common__color__field_indices_by_name,
  1,  nanoem__common__color__number_ranges,
  (ProtobufCMessageInit) nanoem__common__color__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__quaternion__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Quaternion, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Quaternion, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Quaternion, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Quaternion, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__quaternion__field_indices_by_name[] = {
  3,   /* field[3] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange nanoem__common__quaternion__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nanoem__common__quaternion__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Quaternion",
  "Quaternion",
  "Nanoem__Common__Quaternion",
  "nanoem.common",
  sizeof(Nanoem__Common__Quaternion),
  4,
  nanoem__common__quaternion__field_descriptors,
  nanoem__common__quaternion__field_indices_by_name,
  1,  nanoem__common__quaternion__number_ranges,
  (ProtobufCMessageInit) nanoem__common__quaternion__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__interpolation__field_descriptors[4] =
{
  {
    "x0",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Interpolation, x0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y0",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Interpolation, y0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x1",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Interpolation, x1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Interpolation, y1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__interpolation__field_indices_by_name[] = {
  0,   /* field[0] = x0 */
  2,   /* field[2] = x1 */
  1,   /* field[1] = y0 */
  3,   /* field[3] = y1 */
};
static const ProtobufCIntRange nanoem__common__interpolation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nanoem__common__interpolation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Interpolation",
  "Interpolation",
  "Nanoem__Common__Interpolation",
  "nanoem.common",
  sizeof(Nanoem__Common__Interpolation),
  4,
  nanoem__common__interpolation__field_descriptors,
  nanoem__common__interpolation__field_indices_by_name,
  1,  nanoem__common__interpolation__number_ranges,
  (ProtobufCMessageInit) nanoem__common__interpolation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__point__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Point, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Point, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__point__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange nanoem__common__point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nanoem__common__point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Point",
  "Point",
  "Nanoem__Common__Point",
  "nanoem.common",
  sizeof(Nanoem__Common__Point),
  2,
  nanoem__common__point__field_descriptors,
  nanoem__common__point__field_indices_by_name,
  1,  nanoem__common__point__number_ranges,
  (ProtobufCMessageInit) nanoem__common__point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__size__field_descriptors[2] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Size, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Size, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__size__field_indices_by_name[] = {
  1,   /* field[1] = height */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange nanoem__common__size__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nanoem__common__size__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Size",
  "Size",
  "Nanoem__Common__Size",
  "nanoem.common",
  sizeof(Nanoem__Common__Size),
  2,
  nanoem__common__size__field_descriptors,
  nanoem__common__size__field_indices_by_name,
  1,  nanoem__common__size__number_ranges,
  (ProtobufCMessageInit) nanoem__common__size__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__rect__field_descriptors[2] =
{
  {
    "point",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Rect, point),
    &nanoem__common__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Rect, size),
    &nanoem__common__size__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__rect__field_indices_by_name[] = {
  0,   /* field[0] = point */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange nanoem__common__rect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nanoem__common__rect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Rect",
  "Rect",
  "Nanoem__Common__Rect",
  "nanoem.common",
  sizeof(Nanoem__Common__Rect),
  2,
  nanoem__common__rect__field_descriptors,
  nanoem__common__rect__field_indices_by_name,
  1,  nanoem__common__rect__number_ranges,
  (ProtobufCMessageInit) nanoem__common__rect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nanoem__common__rational__field_descriptors[2] =
{
  {
    "denominator",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Rational, denominator),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numerator",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Nanoem__Common__Rational, numerator),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nanoem__common__rational__field_indices_by_name[] = {
  0,   /* field[0] = denominator */
  1,   /* field[1] = numerator */
};
static const ProtobufCIntRange nanoem__common__rational__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nanoem__common__rational__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nanoem.common.Rational",
  "Rational",
  "Nanoem__Common__Rational",
  "nanoem.common",
  sizeof(Nanoem__Common__Rational),
  2,
  nanoem__common__rational__field_descriptors,
  nanoem__common__rational__field_indices_by_name,
  1,  nanoem__common__rational__number_ranges,
  (ProtobufCMessageInit) nanoem__common__rational__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nanoem__common__language__enum_values_by_number[6] =
{
  { "LC_UNKNOWN", "NANOEM__COMMON__LANGUAGE__LC_UNKNOWN", 0 },
  { "LC_JAPANESE", "NANOEM__COMMON__LANGUAGE__LC_JAPANESE", 1 },
  { "LC_ENGLISH", "NANOEM__COMMON__LANGUAGE__LC_ENGLISH", 2 },
  { "LC_SIMPLIFIED_CHINESE", "NANOEM__COMMON__LANGUAGE__LC_SIMPLIFIED_CHINESE", 3 },
  { "LC_TRADITIONAL_CHINESE", "NANOEM__COMMON__LANGUAGE__LC_TRADITIONAL_CHINESE", 4 },
  { "LC_KOREAN", "NANOEM__COMMON__LANGUAGE__LC_KOREAN", 5 },
};
static const ProtobufCIntRange nanoem__common__language__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex nanoem__common__language__enum_values_by_name[6] =
{
  { "LC_ENGLISH", 2 },
  { "LC_JAPANESE", 1 },
  { "LC_KOREAN", 5 },
  { "LC_SIMPLIFIED_CHINESE", 3 },
  { "LC_TRADITIONAL_CHINESE", 4 },
  { "LC_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor nanoem__common__language__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nanoem.common.Language",
  "Language",
  "Nanoem__Common__Language",
  "nanoem.common",
  6,
  nanoem__common__language__enum_values_by_number,
  6,
  nanoem__common__language__enum_values_by_name,
  1,
  nanoem__common__language__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
