/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: effect_dx9ms.proto */

#ifndef PROTOBUF_C_effect_5fdx9ms_2eproto__INCLUDED
#define PROTOBUF_C_effect_5fdx9ms_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Fx9__Effect__Dx9ms__Uniform Fx9__Effect__Dx9ms__Uniform;
typedef struct Fx9__Effect__Dx9ms__Constant Fx9__Effect__Dx9ms__Constant;
typedef struct Fx9__Effect__Dx9ms__Sampler Fx9__Effect__Dx9ms__Sampler;
typedef struct Fx9__Effect__Dx9ms__Attribute Fx9__Effect__Dx9ms__Attribute;
typedef struct Fx9__Effect__Dx9ms__Symbol Fx9__Effect__Dx9ms__Symbol;
typedef struct Fx9__Effect__Dx9ms__SamplerState Fx9__Effect__Dx9ms__SamplerState;
typedef struct Fx9__Effect__Dx9ms__RenderState Fx9__Effect__Dx9ms__RenderState;
typedef struct Fx9__Effect__Dx9ms__Texture Fx9__Effect__Dx9ms__Texture;
typedef struct Fx9__Effect__Dx9ms__Operand Fx9__Effect__Dx9ms__Operand;
typedef struct Fx9__Effect__Dx9ms__Instruction Fx9__Effect__Dx9ms__Instruction;
typedef struct Fx9__Effect__Dx9ms__Preshader Fx9__Effect__Dx9ms__Preshader;
typedef struct Fx9__Effect__Dx9ms__Shader Fx9__Effect__Dx9ms__Shader;
typedef struct Fx9__Effect__Dx9ms__Pass Fx9__Effect__Dx9ms__Pass;


/* --- enums --- */

typedef enum _Fx9__Effect__Dx9ms__ParameterClass {
  FX9__EFFECT__DX9MS__PARAMETER_CLASS__PC_SCALAR = 0,
  FX9__EFFECT__DX9MS__PARAMETER_CLASS__PC_VECTOR = 1,
  FX9__EFFECT__DX9MS__PARAMETER_CLASS__PC_MATRIX_ROWS = 2,
  FX9__EFFECT__DX9MS__PARAMETER_CLASS__PC_MATRIX_COLUMNS = 3,
  FX9__EFFECT__DX9MS__PARAMETER_CLASS__PC_OBJECT = 4,
  FX9__EFFECT__DX9MS__PARAMETER_CLASS__PC_STRUCT = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__PARAMETER_CLASS)
} Fx9__Effect__Dx9ms__ParameterClass;
typedef enum _Fx9__Effect__Dx9ms__ParameterType {
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_VOID = 0,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_BOOL = 1,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_INT = 2,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_FLOAT = 3,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_STRING = 4,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_TEXTURE = 5,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_TEXTURE1D = 6,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_TEXTURE2D = 7,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_TEXTURE3D = 8,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_TEXTURECUBE = 9,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_SAMPLER = 10,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_SAMPLER1D = 11,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_SAMPLER2D = 12,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_SAMPLER3D = 13,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_SAMPLERCUBE = 14,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_PIXELSHADER = 15,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_VERTEXSHADER = 16,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_PIXELFRAGMENT = 17,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_VERTEXFRAGMENT = 18,
  FX9__EFFECT__DX9MS__PARAMETER_TYPE__PT_UNSUPPORTED = 19
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__PARAMETER_TYPE)
} Fx9__Effect__Dx9ms__ParameterType;
typedef enum _Fx9__Effect__Dx9ms__ShaderType {
  FX9__EFFECT__DX9MS__SHADER_TYPE__ST_PIXEL = 1,
  FX9__EFFECT__DX9MS__SHADER_TYPE__ST_VERTEX = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__SHADER_TYPE)
} Fx9__Effect__Dx9ms__ShaderType;
typedef enum _Fx9__Effect__Dx9ms__UniformType {
  FX9__EFFECT__DX9MS__UNIFORM_TYPE__UT_FLOAT = 0,
  FX9__EFFECT__DX9MS__UNIFORM_TYPE__UT_INT = 1,
  FX9__EFFECT__DX9MS__UNIFORM_TYPE__UT_BOOL = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__UNIFORM_TYPE)
} Fx9__Effect__Dx9ms__UniformType;
typedef enum _Fx9__Effect__Dx9ms__SamplerType {
  FX9__EFFECT__DX9MS__SAMPLER_TYPE__SAMPLER_2D = 0,
  FX9__EFFECT__DX9MS__SAMPLER_TYPE__SAMPLER_CUBE = 1,
  FX9__EFFECT__DX9MS__SAMPLER_TYPE__SAMPLER_VOLUME = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__SAMPLER_TYPE)
} Fx9__Effect__Dx9ms__SamplerType;
typedef enum _Fx9__Effect__Dx9ms__AttributeUsage {
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_POSITION = 0,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_BLENDWEIGHT = 1,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_BLENDINDICES = 2,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_NORMAL = 3,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_POINTSIZE = 4,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_TEXCOORD = 5,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_TANGENT = 6,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_BINORMAL = 7,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_TESSFACTOR = 8,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_POSITIONT = 9,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_COLOR = 10,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_FOG = 11,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_DEPTH = 12,
  FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_SAMPLE = 13
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE)
} Fx9__Effect__Dx9ms__AttributeUsage;
typedef enum _Fx9__Effect__Dx9ms__RegisterSet {
  FX9__EFFECT__DX9MS__REGISTER_SET__RS_BOOL = 0,
  FX9__EFFECT__DX9MS__REGISTER_SET__RS_INT4 = 1,
  FX9__EFFECT__DX9MS__REGISTER_SET__RS_FLOAT4 = 2,
  FX9__EFFECT__DX9MS__REGISTER_SET__RS_SAMPLER = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__REGISTER_SET)
} Fx9__Effect__Dx9ms__RegisterSet;
typedef enum _Fx9__Effect__Dx9ms__OperandType {
  FX9__EFFECT__DX9MS__OPERAND_TYPE__PSOT_INPUT = 0,
  FX9__EFFECT__DX9MS__OPERAND_TYPE__PSOT_OUTPUT = 1,
  FX9__EFFECT__DX9MS__OPERAND_TYPE__PSOT_LITERAL = 2,
  FX9__EFFECT__DX9MS__OPERAND_TYPE__PSOT_TEMP = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__OPERAND_TYPE)
} Fx9__Effect__Dx9ms__OperandType;
typedef enum _Fx9__Effect__Dx9ms__Opcode {
  FX9__EFFECT__DX9MS__OPCODE__PSO_NOP = 0,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MOV = 1,
  FX9__EFFECT__DX9MS__OPCODE__PSO_NEG = 2,
  FX9__EFFECT__DX9MS__OPCODE__PSO_RCP = 3,
  FX9__EFFECT__DX9MS__OPCODE__PSO_FRC = 4,
  FX9__EFFECT__DX9MS__OPCODE__PSO_EXP = 5,
  FX9__EFFECT__DX9MS__OPCODE__PSO_LOG = 6,
  FX9__EFFECT__DX9MS__OPCODE__PSO_RSQ = 7,
  FX9__EFFECT__DX9MS__OPCODE__PSO_SIN = 8,
  FX9__EFFECT__DX9MS__OPCODE__PSO_COS = 9,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ASIN = 10,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ACOS = 11,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ATAN = 12,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MIN = 13,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MAX = 14,
  FX9__EFFECT__DX9MS__OPCODE__PSO_LT = 15,
  FX9__EFFECT__DX9MS__OPCODE__PSO_GE = 16,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ADD = 17,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MUL = 18,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ATAN2 = 19,
  FX9__EFFECT__DX9MS__OPCODE__PSO_DIV = 20,
  FX9__EFFECT__DX9MS__OPCODE__PSO_CMP = 21,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MOVC = 22,
  FX9__EFFECT__DX9MS__OPCODE__PSO_DOT = 23,
  FX9__EFFECT__DX9MS__OPCODE__PSO_NOISE = 24,
  FX9__EFFECT__DX9MS__OPCODE__PSO_SCALAR_OPS = 25,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MIN_SCALAR = 26,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MAX_SCALAR = 27,
  FX9__EFFECT__DX9MS__OPCODE__PSO_LT_SCALAR = 28,
  FX9__EFFECT__DX9MS__OPCODE__PSO_GE_SCALAR = 29,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ADD_SCALAR = 30,
  FX9__EFFECT__DX9MS__OPCODE__PSO_MUL_SCALAR = 31,
  FX9__EFFECT__DX9MS__OPCODE__PSO_ATAN2_SCALAR = 32,
  FX9__EFFECT__DX9MS__OPCODE__PSO_DIV_SCALAR = 33,
  FX9__EFFECT__DX9MS__OPCODE__PSO_DOT_SCALAR = 34,
  FX9__EFFECT__DX9MS__OPCODE__PSO_NOISE_SCALAR = 35
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(FX9__EFFECT__DX9MS__OPCODE)
} Fx9__Effect__Dx9ms__Opcode;

/* --- messages --- */

struct  Fx9__Effect__Dx9ms__Uniform
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__UniformType type;
  uint32_t index;
  uint32_t num_elements;
  uint32_t constant_index;
  char *name;
};
#define FX9__EFFECT__DX9MS__UNIFORM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__uniform__descriptor) \
    , FX9__EFFECT__DX9MS__UNIFORM_TYPE__UT_FLOAT, 0, 0, 0, NULL }


struct  Fx9__Effect__Dx9ms__Constant
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__UniformType type;
  uint32_t index;
};
#define FX9__EFFECT__DX9MS__CONSTANT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__constant__descriptor) \
    , FX9__EFFECT__DX9MS__UNIFORM_TYPE__UT_FLOAT, 0 }


struct  Fx9__Effect__Dx9ms__Sampler
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__SamplerType type;
  uint32_t index;
  char *name;
};
#define FX9__EFFECT__DX9MS__SAMPLER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__sampler__descriptor) \
    , FX9__EFFECT__DX9MS__SAMPLER_TYPE__SAMPLER_2D, 0, NULL }


struct  Fx9__Effect__Dx9ms__Attribute
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__AttributeUsage usage;
  uint32_t index;
  char *name;
};
#define FX9__EFFECT__DX9MS__ATTRIBUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__attribute__descriptor) \
    , FX9__EFFECT__DX9MS__ATTRIBUTE_USAGE__AU_POSITION, 0, NULL }


struct  Fx9__Effect__Dx9ms__Symbol
{
  ProtobufCMessage base;
  char *name;
  Fx9__Effect__Dx9ms__RegisterSet register_set;
  uint32_t register_index;
  uint32_t register_count;
};
#define FX9__EFFECT__DX9MS__SYMBOL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__symbol__descriptor) \
    , NULL, FX9__EFFECT__DX9MS__REGISTER_SET__RS_BOOL, 0, 0 }


struct  Fx9__Effect__Dx9ms__SamplerState
{
  ProtobufCMessage base;
  uint32_t key;
  uint32_t value;
};
#define FX9__EFFECT__DX9MS__SAMPLER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__sampler_state__descriptor) \
    , 0, 0 }


struct  Fx9__Effect__Dx9ms__RenderState
{
  ProtobufCMessage base;
  uint32_t key;
  uint32_t value;
};
#define FX9__EFFECT__DX9MS__RENDER_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__render_state__descriptor) \
    , 0, 0 }


struct  Fx9__Effect__Dx9ms__Texture
{
  ProtobufCMessage base;
  char *name;
  uint32_t sampler_index;
  size_t n_sampler_states;
  Fx9__Effect__Dx9ms__SamplerState **sampler_states;
};
#define FX9__EFFECT__DX9MS__TEXTURE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__texture__descriptor) \
    , NULL, 0, 0,NULL }


struct  Fx9__Effect__Dx9ms__Operand
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__OperandType type;
  uint32_t index;
};
#define FX9__EFFECT__DX9MS__OPERAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__operand__descriptor) \
    , FX9__EFFECT__DX9MS__OPERAND_TYPE__PSOT_INPUT, 0 }


struct  Fx9__Effect__Dx9ms__Instruction
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__Opcode opcode;
  uint32_t num_elements;
  size_t n_operands;
  Fx9__Effect__Dx9ms__Operand **operands;
};
#define FX9__EFFECT__DX9MS__INSTRUCTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__instruction__descriptor) \
    , FX9__EFFECT__DX9MS__OPCODE__PSO_NOP, 0, 0,NULL }


struct  Fx9__Effect__Dx9ms__Preshader
{
  ProtobufCMessage base;
  size_t n_literals;
  double *literals;
  uint32_t num_temporary_registers;
  size_t n_symbols;
  Fx9__Effect__Dx9ms__Symbol **symbols;
  size_t n_instructions;
  Fx9__Effect__Dx9ms__Instruction **instructions;
};
#define FX9__EFFECT__DX9MS__PRESHADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__preshader__descriptor) \
    , 0,NULL, 0, 0,NULL, 0,NULL }


struct  Fx9__Effect__Dx9ms__Shader
{
  ProtobufCMessage base;
  uint32_t major_version;
  uint32_t minor_version;
  uint32_t num_intructions;
  Fx9__Effect__Dx9ms__ShaderType type;
  char *code;
  size_t n_uniforms;
  Fx9__Effect__Dx9ms__Uniform **uniforms;
  size_t n_constants;
  Fx9__Effect__Dx9ms__Constant **constants;
  size_t n_samplers;
  Fx9__Effect__Dx9ms__Sampler **samplers;
  size_t n_attributes;
  Fx9__Effect__Dx9ms__Attribute **attributes;
  size_t n_outputs;
  Fx9__Effect__Dx9ms__Attribute **outputs;
  size_t n_symbols;
  Fx9__Effect__Dx9ms__Symbol **symbols;
  Fx9__Effect__Dx9ms__Preshader *preshader;
};
#define FX9__EFFECT__DX9MS__SHADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__shader__descriptor) \
    , 0, 0, 0, FX9__EFFECT__DX9MS__SHADER_TYPE__ST_PIXEL, NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL }


struct  Fx9__Effect__Dx9ms__Pass
{
  ProtobufCMessage base;
  Fx9__Effect__Dx9ms__Shader *vertex_shader;
  Fx9__Effect__Dx9ms__Shader *pixel_shader;
  size_t n_textures;
  Fx9__Effect__Dx9ms__Texture **textures;
  size_t n_render_states;
  Fx9__Effect__Dx9ms__RenderState **render_states;
  size_t n_vertex_textures;
  Fx9__Effect__Dx9ms__Texture **vertex_textures;
};
#define FX9__EFFECT__DX9MS__PASS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fx9__effect__dx9ms__pass__descriptor) \
    , NULL, NULL, 0,NULL, 0,NULL, 0,NULL }


/* Fx9__Effect__Dx9ms__Uniform methods */
void   fx9__effect__dx9ms__uniform__init
                     (Fx9__Effect__Dx9ms__Uniform         *message);
size_t fx9__effect__dx9ms__uniform__get_packed_size
                     (const Fx9__Effect__Dx9ms__Uniform   *message);
size_t fx9__effect__dx9ms__uniform__pack
                     (const Fx9__Effect__Dx9ms__Uniform   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__uniform__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Uniform   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Uniform *
       fx9__effect__dx9ms__uniform__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__uniform__free_unpacked
                     (Fx9__Effect__Dx9ms__Uniform *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Constant methods */
void   fx9__effect__dx9ms__constant__init
                     (Fx9__Effect__Dx9ms__Constant         *message);
size_t fx9__effect__dx9ms__constant__get_packed_size
                     (const Fx9__Effect__Dx9ms__Constant   *message);
size_t fx9__effect__dx9ms__constant__pack
                     (const Fx9__Effect__Dx9ms__Constant   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__constant__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Constant   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Constant *
       fx9__effect__dx9ms__constant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__constant__free_unpacked
                     (Fx9__Effect__Dx9ms__Constant *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Sampler methods */
void   fx9__effect__dx9ms__sampler__init
                     (Fx9__Effect__Dx9ms__Sampler         *message);
size_t fx9__effect__dx9ms__sampler__get_packed_size
                     (const Fx9__Effect__Dx9ms__Sampler   *message);
size_t fx9__effect__dx9ms__sampler__pack
                     (const Fx9__Effect__Dx9ms__Sampler   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__sampler__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Sampler   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Sampler *
       fx9__effect__dx9ms__sampler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__sampler__free_unpacked
                     (Fx9__Effect__Dx9ms__Sampler *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Attribute methods */
void   fx9__effect__dx9ms__attribute__init
                     (Fx9__Effect__Dx9ms__Attribute         *message);
size_t fx9__effect__dx9ms__attribute__get_packed_size
                     (const Fx9__Effect__Dx9ms__Attribute   *message);
size_t fx9__effect__dx9ms__attribute__pack
                     (const Fx9__Effect__Dx9ms__Attribute   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__attribute__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Attribute   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Attribute *
       fx9__effect__dx9ms__attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__attribute__free_unpacked
                     (Fx9__Effect__Dx9ms__Attribute *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Symbol methods */
void   fx9__effect__dx9ms__symbol__init
                     (Fx9__Effect__Dx9ms__Symbol         *message);
size_t fx9__effect__dx9ms__symbol__get_packed_size
                     (const Fx9__Effect__Dx9ms__Symbol   *message);
size_t fx9__effect__dx9ms__symbol__pack
                     (const Fx9__Effect__Dx9ms__Symbol   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__symbol__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Symbol   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Symbol *
       fx9__effect__dx9ms__symbol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__symbol__free_unpacked
                     (Fx9__Effect__Dx9ms__Symbol *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__SamplerState methods */
void   fx9__effect__dx9ms__sampler_state__init
                     (Fx9__Effect__Dx9ms__SamplerState         *message);
size_t fx9__effect__dx9ms__sampler_state__get_packed_size
                     (const Fx9__Effect__Dx9ms__SamplerState   *message);
size_t fx9__effect__dx9ms__sampler_state__pack
                     (const Fx9__Effect__Dx9ms__SamplerState   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__sampler_state__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__SamplerState   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__SamplerState *
       fx9__effect__dx9ms__sampler_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__sampler_state__free_unpacked
                     (Fx9__Effect__Dx9ms__SamplerState *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__RenderState methods */
void   fx9__effect__dx9ms__render_state__init
                     (Fx9__Effect__Dx9ms__RenderState         *message);
size_t fx9__effect__dx9ms__render_state__get_packed_size
                     (const Fx9__Effect__Dx9ms__RenderState   *message);
size_t fx9__effect__dx9ms__render_state__pack
                     (const Fx9__Effect__Dx9ms__RenderState   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__render_state__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__RenderState   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__RenderState *
       fx9__effect__dx9ms__render_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__render_state__free_unpacked
                     (Fx9__Effect__Dx9ms__RenderState *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Texture methods */
void   fx9__effect__dx9ms__texture__init
                     (Fx9__Effect__Dx9ms__Texture         *message);
size_t fx9__effect__dx9ms__texture__get_packed_size
                     (const Fx9__Effect__Dx9ms__Texture   *message);
size_t fx9__effect__dx9ms__texture__pack
                     (const Fx9__Effect__Dx9ms__Texture   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__texture__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Texture   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Texture *
       fx9__effect__dx9ms__texture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__texture__free_unpacked
                     (Fx9__Effect__Dx9ms__Texture *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Operand methods */
void   fx9__effect__dx9ms__operand__init
                     (Fx9__Effect__Dx9ms__Operand         *message);
size_t fx9__effect__dx9ms__operand__get_packed_size
                     (const Fx9__Effect__Dx9ms__Operand   *message);
size_t fx9__effect__dx9ms__operand__pack
                     (const Fx9__Effect__Dx9ms__Operand   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__operand__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Operand   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Operand *
       fx9__effect__dx9ms__operand__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__operand__free_unpacked
                     (Fx9__Effect__Dx9ms__Operand *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Instruction methods */
void   fx9__effect__dx9ms__instruction__init
                     (Fx9__Effect__Dx9ms__Instruction         *message);
size_t fx9__effect__dx9ms__instruction__get_packed_size
                     (const Fx9__Effect__Dx9ms__Instruction   *message);
size_t fx9__effect__dx9ms__instruction__pack
                     (const Fx9__Effect__Dx9ms__Instruction   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__instruction__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Instruction   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Instruction *
       fx9__effect__dx9ms__instruction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__instruction__free_unpacked
                     (Fx9__Effect__Dx9ms__Instruction *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Preshader methods */
void   fx9__effect__dx9ms__preshader__init
                     (Fx9__Effect__Dx9ms__Preshader         *message);
size_t fx9__effect__dx9ms__preshader__get_packed_size
                     (const Fx9__Effect__Dx9ms__Preshader   *message);
size_t fx9__effect__dx9ms__preshader__pack
                     (const Fx9__Effect__Dx9ms__Preshader   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__preshader__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Preshader   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Preshader *
       fx9__effect__dx9ms__preshader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__preshader__free_unpacked
                     (Fx9__Effect__Dx9ms__Preshader *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Shader methods */
void   fx9__effect__dx9ms__shader__init
                     (Fx9__Effect__Dx9ms__Shader         *message);
size_t fx9__effect__dx9ms__shader__get_packed_size
                     (const Fx9__Effect__Dx9ms__Shader   *message);
size_t fx9__effect__dx9ms__shader__pack
                     (const Fx9__Effect__Dx9ms__Shader   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__shader__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Shader   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Shader *
       fx9__effect__dx9ms__shader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__shader__free_unpacked
                     (Fx9__Effect__Dx9ms__Shader *message,
                      ProtobufCAllocator *allocator);
/* Fx9__Effect__Dx9ms__Pass methods */
void   fx9__effect__dx9ms__pass__init
                     (Fx9__Effect__Dx9ms__Pass         *message);
size_t fx9__effect__dx9ms__pass__get_packed_size
                     (const Fx9__Effect__Dx9ms__Pass   *message);
size_t fx9__effect__dx9ms__pass__pack
                     (const Fx9__Effect__Dx9ms__Pass   *message,
                      uint8_t             *out);
size_t fx9__effect__dx9ms__pass__pack_to_buffer
                     (const Fx9__Effect__Dx9ms__Pass   *message,
                      ProtobufCBuffer     *buffer);
Fx9__Effect__Dx9ms__Pass *
       fx9__effect__dx9ms__pass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fx9__effect__dx9ms__pass__free_unpacked
                     (Fx9__Effect__Dx9ms__Pass *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Fx9__Effect__Dx9ms__Uniform_Closure)
                 (const Fx9__Effect__Dx9ms__Uniform *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Constant_Closure)
                 (const Fx9__Effect__Dx9ms__Constant *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Sampler_Closure)
                 (const Fx9__Effect__Dx9ms__Sampler *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Attribute_Closure)
                 (const Fx9__Effect__Dx9ms__Attribute *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Symbol_Closure)
                 (const Fx9__Effect__Dx9ms__Symbol *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__SamplerState_Closure)
                 (const Fx9__Effect__Dx9ms__SamplerState *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__RenderState_Closure)
                 (const Fx9__Effect__Dx9ms__RenderState *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Texture_Closure)
                 (const Fx9__Effect__Dx9ms__Texture *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Operand_Closure)
                 (const Fx9__Effect__Dx9ms__Operand *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Instruction_Closure)
                 (const Fx9__Effect__Dx9ms__Instruction *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Preshader_Closure)
                 (const Fx9__Effect__Dx9ms__Preshader *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Shader_Closure)
                 (const Fx9__Effect__Dx9ms__Shader *message,
                  void *closure_data);
typedef void (*Fx9__Effect__Dx9ms__Pass_Closure)
                 (const Fx9__Effect__Dx9ms__Pass *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__parameter_class__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__parameter_type__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__shader_type__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__uniform_type__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__sampler_type__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__attribute_usage__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__register_set__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__operand_type__descriptor;
extern const ProtobufCEnumDescriptor    fx9__effect__dx9ms__opcode__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__uniform__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__constant__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__sampler__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__attribute__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__symbol__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__sampler_state__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__render_state__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__texture__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__operand__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__instruction__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__preshader__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__shader__descriptor;
extern const ProtobufCMessageDescriptor fx9__effect__dx9ms__pass__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_effect_5fdx9ms_2eproto__INCLUDED */
