/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: effect_dx9bc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "effect_dx9bc.pb-c.h"
void   fx9__effect__dx9bc__constant__init
                     (Fx9__Effect__Dx9bc__Constant         *message)
{
  static const Fx9__Effect__Dx9bc__Constant init_value = FX9__EFFECT__DX9BC__CONSTANT__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__constant__get_packed_size
                     (const Fx9__Effect__Dx9bc__Constant *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__constant__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__constant__pack
                     (const Fx9__Effect__Dx9bc__Constant *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__constant__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__constant__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__Constant *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__constant__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__Constant *
       fx9__effect__dx9bc__constant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__Constant *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__constant__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__constant__free_unpacked
                     (Fx9__Effect__Dx9bc__Constant *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__constant__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__dx9bc__sampler__init
                     (Fx9__Effect__Dx9bc__Sampler         *message)
{
  static const Fx9__Effect__Dx9bc__Sampler init_value = FX9__EFFECT__DX9BC__SAMPLER__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__sampler__get_packed_size
                     (const Fx9__Effect__Dx9bc__Sampler *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__sampler__pack
                     (const Fx9__Effect__Dx9bc__Sampler *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__sampler__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__Sampler *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__Sampler *
       fx9__effect__dx9bc__sampler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__Sampler *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__sampler__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__sampler__free_unpacked
                     (Fx9__Effect__Dx9bc__Sampler *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__dx9bc__sampler_state__init
                     (Fx9__Effect__Dx9bc__SamplerState         *message)
{
  static const Fx9__Effect__Dx9bc__SamplerState init_value = FX9__EFFECT__DX9BC__SAMPLER_STATE__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__sampler_state__get_packed_size
                     (const Fx9__Effect__Dx9bc__SamplerState *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__sampler_state__pack
                     (const Fx9__Effect__Dx9bc__SamplerState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__sampler_state__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__SamplerState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__SamplerState *
       fx9__effect__dx9bc__sampler_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__SamplerState *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__sampler_state__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__sampler_state__free_unpacked
                     (Fx9__Effect__Dx9bc__SamplerState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__sampler_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__dx9bc__render_state__init
                     (Fx9__Effect__Dx9bc__RenderState         *message)
{
  static const Fx9__Effect__Dx9bc__RenderState init_value = FX9__EFFECT__DX9BC__RENDER_STATE__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__render_state__get_packed_size
                     (const Fx9__Effect__Dx9bc__RenderState *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__render_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__render_state__pack
                     (const Fx9__Effect__Dx9bc__RenderState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__render_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__render_state__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__RenderState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__render_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__RenderState *
       fx9__effect__dx9bc__render_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__RenderState *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__render_state__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__render_state__free_unpacked
                     (Fx9__Effect__Dx9bc__RenderState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__render_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__dx9bc__texture__init
                     (Fx9__Effect__Dx9bc__Texture         *message)
{
  static const Fx9__Effect__Dx9bc__Texture init_value = FX9__EFFECT__DX9BC__TEXTURE__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__texture__get_packed_size
                     (const Fx9__Effect__Dx9bc__Texture *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__texture__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__texture__pack
                     (const Fx9__Effect__Dx9bc__Texture *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__texture__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__texture__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__Texture *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__texture__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__Texture *
       fx9__effect__dx9bc__texture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__Texture *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__texture__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__texture__free_unpacked
                     (Fx9__Effect__Dx9bc__Texture *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__texture__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__dx9bc__shader__init
                     (Fx9__Effect__Dx9bc__Shader         *message)
{
  static const Fx9__Effect__Dx9bc__Shader init_value = FX9__EFFECT__DX9BC__SHADER__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__shader__get_packed_size
                     (const Fx9__Effect__Dx9bc__Shader *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__shader__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__shader__pack
                     (const Fx9__Effect__Dx9bc__Shader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__shader__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__shader__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__Shader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__shader__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__Shader *
       fx9__effect__dx9bc__shader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__Shader *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__shader__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__shader__free_unpacked
                     (Fx9__Effect__Dx9bc__Shader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__shader__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__dx9bc__pass__init
                     (Fx9__Effect__Dx9bc__Pass         *message)
{
  static const Fx9__Effect__Dx9bc__Pass init_value = FX9__EFFECT__DX9BC__PASS__INIT;
  *message = init_value;
}
size_t fx9__effect__dx9bc__pass__get_packed_size
                     (const Fx9__Effect__Dx9bc__Pass *message)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__pass__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__dx9bc__pass__pack
                     (const Fx9__Effect__Dx9bc__Pass *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__pass__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__dx9bc__pass__pack_to_buffer
                     (const Fx9__Effect__Dx9bc__Pass *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__dx9bc__pass__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Dx9bc__Pass *
       fx9__effect__dx9bc__pass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Dx9bc__Pass *)
     protobuf_c_message_unpack (&fx9__effect__dx9bc__pass__descriptor,
                                allocator, len, data);
}
void   fx9__effect__dx9bc__pass__free_unpacked
                     (Fx9__Effect__Dx9bc__Pass *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__dx9bc__pass__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__constant__field_descriptors[11] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_set",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, register_set),
    &fx9__effect__dx9bc__register_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, register_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_count",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, register_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, class_),
    &fx9__effect__dx9bc__parameter_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, type),
    &fx9__effect__dx9bc__parameter_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_rows",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, num_rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_columns",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, num_columns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_elements",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, num_elements),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "struct_members",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, struct_members),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_value",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Constant, default_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__constant__field_indices_by_name[] = {
  4,   /* field[4] = class */
  10,   /* field[10] = default_value */
  0,   /* field[0] = name */
  7,   /* field[7] = num_columns */
  8,   /* field[8] = num_elements */
  6,   /* field[6] = num_rows */
  3,   /* field[3] = register_count */
  2,   /* field[2] = register_index */
  1,   /* field[1] = register_set */
  9,   /* field[9] = struct_members */
  5,   /* field[5] = type */
};
static const ProtobufCIntRange fx9__effect__dx9bc__constant__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__constant__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.Constant",
  "Constant",
  "Fx9__Effect__Dx9bc__Constant",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__Constant),
  11,
  fx9__effect__dx9bc__constant__field_descriptors,
  fx9__effect__dx9bc__constant__field_indices_by_name,
  1,  fx9__effect__dx9bc__constant__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__constant__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__sampler__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Sampler, type),
    &fx9__effect__dx9bc__sampler_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Sampler, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Sampler, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__sampler__field_indices_by_name[] = {
  1,   /* field[1] = index */
  2,   /* field[2] = name */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange fx9__effect__dx9bc__sampler__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__sampler__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.Sampler",
  "Sampler",
  "Fx9__Effect__Dx9bc__Sampler",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__Sampler),
  3,
  fx9__effect__dx9bc__sampler__field_descriptors,
  fx9__effect__dx9bc__sampler__field_indices_by_name,
  1,  fx9__effect__dx9bc__sampler__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__sampler__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__sampler_state__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__SamplerState, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__SamplerState, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__sampler_state__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange fx9__effect__dx9bc__sampler_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__sampler_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.SamplerState",
  "SamplerState",
  "Fx9__Effect__Dx9bc__SamplerState",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__SamplerState),
  2,
  fx9__effect__dx9bc__sampler_state__field_descriptors,
  fx9__effect__dx9bc__sampler_state__field_indices_by_name,
  1,  fx9__effect__dx9bc__sampler_state__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__sampler_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__render_state__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__RenderState, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__RenderState, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__render_state__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange fx9__effect__dx9bc__render_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__render_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.RenderState",
  "RenderState",
  "Fx9__Effect__Dx9bc__RenderState",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__RenderState),
  2,
  fx9__effect__dx9bc__render_state__field_descriptors,
  fx9__effect__dx9bc__render_state__field_indices_by_name,
  1,  fx9__effect__dx9bc__render_state__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__render_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__texture__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Texture, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampler_index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Texture, sampler_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampler_states",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Dx9bc__Texture, n_sampler_states),
    offsetof(Fx9__Effect__Dx9bc__Texture, sampler_states),
    &fx9__effect__dx9bc__sampler_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__texture__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = sampler_index */
  2,   /* field[2] = sampler_states */
};
static const ProtobufCIntRange fx9__effect__dx9bc__texture__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__texture__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.Texture",
  "Texture",
  "Fx9__Effect__Dx9bc__Texture",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__Texture),
  3,
  fx9__effect__dx9bc__texture__field_descriptors,
  fx9__effect__dx9bc__texture__field_indices_by_name,
  1,  fx9__effect__dx9bc__texture__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__texture__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__shader__field_descriptors[7] =
{
  {
    "major_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Shader, major_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Shader, minor_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_intructions",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Shader, num_intructions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Shader, type),
    &fx9__effect__dx9bc__shader_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "assembly",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Shader, assembly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "constants",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Dx9bc__Shader, n_constants),
    offsetof(Fx9__Effect__Dx9bc__Shader, constants),
    &fx9__effect__dx9bc__constant__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samplers",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Dx9bc__Shader, n_samplers),
    offsetof(Fx9__Effect__Dx9bc__Shader, samplers),
    &fx9__effect__dx9bc__sampler__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__shader__field_indices_by_name[] = {
  4,   /* field[4] = assembly */
  5,   /* field[5] = constants */
  0,   /* field[0] = major_version */
  1,   /* field[1] = minor_version */
  2,   /* field[2] = num_intructions */
  6,   /* field[6] = samplers */
  3,   /* field[3] = type */
};
static const ProtobufCIntRange fx9__effect__dx9bc__shader__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__shader__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.Shader",
  "Shader",
  "Fx9__Effect__Dx9bc__Shader",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__Shader),
  7,
  fx9__effect__dx9bc__shader__field_descriptors,
  fx9__effect__dx9bc__shader__field_indices_by_name,
  1,  fx9__effect__dx9bc__shader__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__shader__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__dx9bc__pass__field_descriptors[5] =
{
  {
    "vertex_shader",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Pass, vertex_shader),
    &fx9__effect__dx9bc__shader__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_shader",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Dx9bc__Pass, pixel_shader),
    &fx9__effect__dx9bc__shader__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "textures",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Dx9bc__Pass, n_textures),
    offsetof(Fx9__Effect__Dx9bc__Pass, textures),
    &fx9__effect__dx9bc__texture__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "render_states",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Dx9bc__Pass, n_render_states),
    offsetof(Fx9__Effect__Dx9bc__Pass, render_states),
    &fx9__effect__dx9bc__render_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertex_textures",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Dx9bc__Pass, n_vertex_textures),
    offsetof(Fx9__Effect__Dx9bc__Pass, vertex_textures),
    &fx9__effect__dx9bc__texture__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__dx9bc__pass__field_indices_by_name[] = {
  1,   /* field[1] = pixel_shader */
  3,   /* field[3] = render_states */
  2,   /* field[2] = textures */
  0,   /* field[0] = vertex_shader */
  4,   /* field[4] = vertex_textures */
};
static const ProtobufCIntRange fx9__effect__dx9bc__pass__number_ranges[2 + 1] =
{
  { 2, 0 },
  { 5, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor fx9__effect__dx9bc__pass__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.Pass",
  "Pass",
  "Fx9__Effect__Dx9bc__Pass",
  "fx9.effect.dx9bc",
  sizeof(Fx9__Effect__Dx9bc__Pass),
  5,
  fx9__effect__dx9bc__pass__field_descriptors,
  fx9__effect__dx9bc__pass__field_indices_by_name,
  2,  fx9__effect__dx9bc__pass__number_ranges,
  (ProtobufCMessageInit) fx9__effect__dx9bc__pass__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue fx9__effect__dx9bc__parameter_class__enum_values_by_number[6] =
{
  { "PC_SCALAR", "FX9__EFFECT__DX9BC__PARAMETER_CLASS__PC_SCALAR", 0 },
  { "PC_VECTOR", "FX9__EFFECT__DX9BC__PARAMETER_CLASS__PC_VECTOR", 1 },
  { "PC_MATRIX_ROWS", "FX9__EFFECT__DX9BC__PARAMETER_CLASS__PC_MATRIX_ROWS", 2 },
  { "PC_MATRIX_COLUMNS", "FX9__EFFECT__DX9BC__PARAMETER_CLASS__PC_MATRIX_COLUMNS", 3 },
  { "PC_OBJECT", "FX9__EFFECT__DX9BC__PARAMETER_CLASS__PC_OBJECT", 4 },
  { "PC_STRUCT", "FX9__EFFECT__DX9BC__PARAMETER_CLASS__PC_STRUCT", 5 },
};
static const ProtobufCIntRange fx9__effect__dx9bc__parameter_class__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex fx9__effect__dx9bc__parameter_class__enum_values_by_name[6] =
{
  { "PC_MATRIX_COLUMNS", 3 },
  { "PC_MATRIX_ROWS", 2 },
  { "PC_OBJECT", 4 },
  { "PC_SCALAR", 0 },
  { "PC_STRUCT", 5 },
  { "PC_VECTOR", 1 },
};
const ProtobufCEnumDescriptor fx9__effect__dx9bc__parameter_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.ParameterClass",
  "ParameterClass",
  "Fx9__Effect__Dx9bc__ParameterClass",
  "fx9.effect.dx9bc",
  6,
  fx9__effect__dx9bc__parameter_class__enum_values_by_number,
  6,
  fx9__effect__dx9bc__parameter_class__enum_values_by_name,
  1,
  fx9__effect__dx9bc__parameter_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__dx9bc__parameter_type__enum_values_by_number[20] =
{
  { "PT_VOID", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_VOID", 0 },
  { "PT_BOOL", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_BOOL", 1 },
  { "PT_INT", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_INT", 2 },
  { "PT_FLOAT", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_FLOAT", 3 },
  { "PT_STRING", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_STRING", 4 },
  { "PT_TEXTURE", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_TEXTURE", 5 },
  { "PT_TEXTURE1D", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_TEXTURE1D", 6 },
  { "PT_TEXTURE2D", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_TEXTURE2D", 7 },
  { "PT_TEXTURE3D", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_TEXTURE3D", 8 },
  { "PT_TEXTURECUBE", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_TEXTURECUBE", 9 },
  { "PT_SAMPLER", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_SAMPLER", 10 },
  { "PT_SAMPLER1D", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_SAMPLER1D", 11 },
  { "PT_SAMPLER2D", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_SAMPLER2D", 12 },
  { "PT_SAMPLER3D", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_SAMPLER3D", 13 },
  { "PT_SAMPLERCUBE", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_SAMPLERCUBE", 14 },
  { "PT_PIXELSHADER", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_PIXELSHADER", 15 },
  { "PT_VERTEXSHADER", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_VERTEXSHADER", 16 },
  { "PT_PIXELFRAGMENT", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_PIXELFRAGMENT", 17 },
  { "PT_VERTEXFRAGMENT", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_VERTEXFRAGMENT", 18 },
  { "PT_UNSUPPORTED", "FX9__EFFECT__DX9BC__PARAMETER_TYPE__PT_UNSUPPORTED", 19 },
};
static const ProtobufCIntRange fx9__effect__dx9bc__parameter_type__value_ranges[] = {
{0, 0},{0, 20}
};
static const ProtobufCEnumValueIndex fx9__effect__dx9bc__parameter_type__enum_values_by_name[20] =
{
  { "PT_BOOL", 1 },
  { "PT_FLOAT", 3 },
  { "PT_INT", 2 },
  { "PT_PIXELFRAGMENT", 17 },
  { "PT_PIXELSHADER", 15 },
  { "PT_SAMPLER", 10 },
  { "PT_SAMPLER1D", 11 },
  { "PT_SAMPLER2D", 12 },
  { "PT_SAMPLER3D", 13 },
  { "PT_SAMPLERCUBE", 14 },
  { "PT_STRING", 4 },
  { "PT_TEXTURE", 5 },
  { "PT_TEXTURE1D", 6 },
  { "PT_TEXTURE2D", 7 },
  { "PT_TEXTURE3D", 8 },
  { "PT_TEXTURECUBE", 9 },
  { "PT_UNSUPPORTED", 19 },
  { "PT_VERTEXFRAGMENT", 18 },
  { "PT_VERTEXSHADER", 16 },
  { "PT_VOID", 0 },
};
const ProtobufCEnumDescriptor fx9__effect__dx9bc__parameter_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.ParameterType",
  "ParameterType",
  "Fx9__Effect__Dx9bc__ParameterType",
  "fx9.effect.dx9bc",
  20,
  fx9__effect__dx9bc__parameter_type__enum_values_by_number,
  20,
  fx9__effect__dx9bc__parameter_type__enum_values_by_name,
  1,
  fx9__effect__dx9bc__parameter_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__dx9bc__shader_type__enum_values_by_number[2] =
{
  { "ST_PIXEL", "FX9__EFFECT__DX9BC__SHADER_TYPE__ST_PIXEL", 1 },
  { "ST_VERTEX", "FX9__EFFECT__DX9BC__SHADER_TYPE__ST_VERTEX", 2 },
};
static const ProtobufCIntRange fx9__effect__dx9bc__shader_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex fx9__effect__dx9bc__shader_type__enum_values_by_name[2] =
{
  { "ST_PIXEL", 0 },
  { "ST_VERTEX", 1 },
};
const ProtobufCEnumDescriptor fx9__effect__dx9bc__shader_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.ShaderType",
  "ShaderType",
  "Fx9__Effect__Dx9bc__ShaderType",
  "fx9.effect.dx9bc",
  2,
  fx9__effect__dx9bc__shader_type__enum_values_by_number,
  2,
  fx9__effect__dx9bc__shader_type__enum_values_by_name,
  1,
  fx9__effect__dx9bc__shader_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__dx9bc__register_set__enum_values_by_number[4] =
{
  { "RS_BOOL", "FX9__EFFECT__DX9BC__REGISTER_SET__RS_BOOL", 0 },
  { "RS_INT4", "FX9__EFFECT__DX9BC__REGISTER_SET__RS_INT4", 1 },
  { "RS_FLOAT4", "FX9__EFFECT__DX9BC__REGISTER_SET__RS_FLOAT4", 2 },
  { "RS_SAMPLER", "FX9__EFFECT__DX9BC__REGISTER_SET__RS_SAMPLER", 3 },
};
static const ProtobufCIntRange fx9__effect__dx9bc__register_set__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex fx9__effect__dx9bc__register_set__enum_values_by_name[4] =
{
  { "RS_BOOL", 0 },
  { "RS_FLOAT4", 2 },
  { "RS_INT4", 1 },
  { "RS_SAMPLER", 3 },
};
const ProtobufCEnumDescriptor fx9__effect__dx9bc__register_set__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.RegisterSet",
  "RegisterSet",
  "Fx9__Effect__Dx9bc__RegisterSet",
  "fx9.effect.dx9bc",
  4,
  fx9__effect__dx9bc__register_set__enum_values_by_number,
  4,
  fx9__effect__dx9bc__register_set__enum_values_by_name,
  1,
  fx9__effect__dx9bc__register_set__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__dx9bc__sampler_type__enum_values_by_number[3] =
{
  { "SAMPLER_2D", "FX9__EFFECT__DX9BC__SAMPLER_TYPE__SAMPLER_2D", 0 },
  { "SAMPLER_CUBE", "FX9__EFFECT__DX9BC__SAMPLER_TYPE__SAMPLER_CUBE", 1 },
  { "SAMPLER_VOLUME", "FX9__EFFECT__DX9BC__SAMPLER_TYPE__SAMPLER_VOLUME", 2 },
};
static const ProtobufCIntRange fx9__effect__dx9bc__sampler_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex fx9__effect__dx9bc__sampler_type__enum_values_by_name[3] =
{
  { "SAMPLER_2D", 0 },
  { "SAMPLER_CUBE", 1 },
  { "SAMPLER_VOLUME", 2 },
};
const ProtobufCEnumDescriptor fx9__effect__dx9bc__sampler_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.dx9bc.SamplerType",
  "SamplerType",
  "Fx9__Effect__Dx9bc__SamplerType",
  "fx9.effect.dx9bc",
  3,
  fx9__effect__dx9bc__sampler_type__enum_values_by_number,
  3,
  fx9__effect__dx9bc__sampler_type__enum_values_by_name,
  1,
  fx9__effect__dx9bc__sampler_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
