/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: effect_msl.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "effect_msl.pb-c.h"
void   fx9__effect__msl__uniform__init
                     (Fx9__Effect__Msl__Uniform         *message)
{
  static const Fx9__Effect__Msl__Uniform init_value = FX9__EFFECT__MSL__UNIFORM__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__uniform__get_packed_size
                     (const Fx9__Effect__Msl__Uniform *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__uniform__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__uniform__pack
                     (const Fx9__Effect__Msl__Uniform *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__uniform__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__uniform__pack_to_buffer
                     (const Fx9__Effect__Msl__Uniform *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__uniform__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Uniform *
       fx9__effect__msl__uniform__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Uniform *)
     protobuf_c_message_unpack (&fx9__effect__msl__uniform__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__uniform__free_unpacked
                     (Fx9__Effect__Msl__Uniform *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__uniform__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__constant__init
                     (Fx9__Effect__Msl__Constant         *message)
{
  static const Fx9__Effect__Msl__Constant init_value = FX9__EFFECT__MSL__CONSTANT__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__constant__get_packed_size
                     (const Fx9__Effect__Msl__Constant *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__constant__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__constant__pack
                     (const Fx9__Effect__Msl__Constant *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__constant__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__constant__pack_to_buffer
                     (const Fx9__Effect__Msl__Constant *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__constant__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Constant *
       fx9__effect__msl__constant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Constant *)
     protobuf_c_message_unpack (&fx9__effect__msl__constant__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__constant__free_unpacked
                     (Fx9__Effect__Msl__Constant *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__constant__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__sampler__init
                     (Fx9__Effect__Msl__Sampler         *message)
{
  static const Fx9__Effect__Msl__Sampler init_value = FX9__EFFECT__MSL__SAMPLER__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__sampler__get_packed_size
                     (const Fx9__Effect__Msl__Sampler *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__sampler__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__sampler__pack
                     (const Fx9__Effect__Msl__Sampler *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__sampler__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__sampler__pack_to_buffer
                     (const Fx9__Effect__Msl__Sampler *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__sampler__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Sampler *
       fx9__effect__msl__sampler__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Sampler *)
     protobuf_c_message_unpack (&fx9__effect__msl__sampler__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__sampler__free_unpacked
                     (Fx9__Effect__Msl__Sampler *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__sampler__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__attribute__init
                     (Fx9__Effect__Msl__Attribute         *message)
{
  static const Fx9__Effect__Msl__Attribute init_value = FX9__EFFECT__MSL__ATTRIBUTE__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__attribute__get_packed_size
                     (const Fx9__Effect__Msl__Attribute *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__attribute__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__attribute__pack
                     (const Fx9__Effect__Msl__Attribute *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__attribute__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__attribute__pack_to_buffer
                     (const Fx9__Effect__Msl__Attribute *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__attribute__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Attribute *
       fx9__effect__msl__attribute__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Attribute *)
     protobuf_c_message_unpack (&fx9__effect__msl__attribute__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__attribute__free_unpacked
                     (Fx9__Effect__Msl__Attribute *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__attribute__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__symbol__init
                     (Fx9__Effect__Msl__Symbol         *message)
{
  static const Fx9__Effect__Msl__Symbol init_value = FX9__EFFECT__MSL__SYMBOL__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__symbol__get_packed_size
                     (const Fx9__Effect__Msl__Symbol *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__symbol__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__symbol__pack
                     (const Fx9__Effect__Msl__Symbol *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__symbol__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__symbol__pack_to_buffer
                     (const Fx9__Effect__Msl__Symbol *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__symbol__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Symbol *
       fx9__effect__msl__symbol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Symbol *)
     protobuf_c_message_unpack (&fx9__effect__msl__symbol__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__symbol__free_unpacked
                     (Fx9__Effect__Msl__Symbol *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__symbol__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__sampler_state__init
                     (Fx9__Effect__Msl__SamplerState         *message)
{
  static const Fx9__Effect__Msl__SamplerState init_value = FX9__EFFECT__MSL__SAMPLER_STATE__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__sampler_state__get_packed_size
                     (const Fx9__Effect__Msl__SamplerState *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__sampler_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__sampler_state__pack
                     (const Fx9__Effect__Msl__SamplerState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__sampler_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__sampler_state__pack_to_buffer
                     (const Fx9__Effect__Msl__SamplerState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__sampler_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__SamplerState *
       fx9__effect__msl__sampler_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__SamplerState *)
     protobuf_c_message_unpack (&fx9__effect__msl__sampler_state__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__sampler_state__free_unpacked
                     (Fx9__Effect__Msl__SamplerState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__sampler_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__render_state__init
                     (Fx9__Effect__Msl__RenderState         *message)
{
  static const Fx9__Effect__Msl__RenderState init_value = FX9__EFFECT__MSL__RENDER_STATE__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__render_state__get_packed_size
                     (const Fx9__Effect__Msl__RenderState *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__render_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__render_state__pack
                     (const Fx9__Effect__Msl__RenderState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__render_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__render_state__pack_to_buffer
                     (const Fx9__Effect__Msl__RenderState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__render_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__RenderState *
       fx9__effect__msl__render_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__RenderState *)
     protobuf_c_message_unpack (&fx9__effect__msl__render_state__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__render_state__free_unpacked
                     (Fx9__Effect__Msl__RenderState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__render_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__texture__init
                     (Fx9__Effect__Msl__Texture         *message)
{
  static const Fx9__Effect__Msl__Texture init_value = FX9__EFFECT__MSL__TEXTURE__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__texture__get_packed_size
                     (const Fx9__Effect__Msl__Texture *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__texture__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__texture__pack
                     (const Fx9__Effect__Msl__Texture *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__texture__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__texture__pack_to_buffer
                     (const Fx9__Effect__Msl__Texture *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__texture__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Texture *
       fx9__effect__msl__texture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Texture *)
     protobuf_c_message_unpack (&fx9__effect__msl__texture__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__texture__free_unpacked
                     (Fx9__Effect__Msl__Texture *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__texture__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__shader__init
                     (Fx9__Effect__Msl__Shader         *message)
{
  static const Fx9__Effect__Msl__Shader init_value = FX9__EFFECT__MSL__SHADER__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__shader__get_packed_size
                     (const Fx9__Effect__Msl__Shader *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__shader__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__shader__pack
                     (const Fx9__Effect__Msl__Shader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__shader__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__shader__pack_to_buffer
                     (const Fx9__Effect__Msl__Shader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__shader__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Shader *
       fx9__effect__msl__shader__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Shader *)
     protobuf_c_message_unpack (&fx9__effect__msl__shader__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__shader__free_unpacked
                     (Fx9__Effect__Msl__Shader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__shader__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fx9__effect__msl__pass__init
                     (Fx9__Effect__Msl__Pass         *message)
{
  static const Fx9__Effect__Msl__Pass init_value = FX9__EFFECT__MSL__PASS__INIT;
  *message = init_value;
}
size_t fx9__effect__msl__pass__get_packed_size
                     (const Fx9__Effect__Msl__Pass *message)
{
  assert(message->base.descriptor == &fx9__effect__msl__pass__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fx9__effect__msl__pass__pack
                     (const Fx9__Effect__Msl__Pass *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fx9__effect__msl__pass__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fx9__effect__msl__pass__pack_to_buffer
                     (const Fx9__Effect__Msl__Pass *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fx9__effect__msl__pass__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Fx9__Effect__Msl__Pass *
       fx9__effect__msl__pass__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Fx9__Effect__Msl__Pass *)
     protobuf_c_message_unpack (&fx9__effect__msl__pass__descriptor,
                                allocator, len, data);
}
void   fx9__effect__msl__pass__free_unpacked
                     (Fx9__Effect__Msl__Pass *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fx9__effect__msl__pass__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fx9__effect__msl__uniform__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Uniform, type),
    &fx9__effect__msl__uniform_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Uniform, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_elements",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Uniform, num_elements),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "constant_index",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Uniform, constant_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Uniform, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__uniform__field_indices_by_name[] = {
  3,   /* field[3] = constant_index */
  1,   /* field[1] = index */
  4,   /* field[4] = name */
  2,   /* field[2] = num_elements */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange fx9__effect__msl__uniform__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__uniform__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Uniform",
  "Uniform",
  "Fx9__Effect__Msl__Uniform",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Uniform),
  5,
  fx9__effect__msl__uniform__field_descriptors,
  fx9__effect__msl__uniform__field_indices_by_name,
  1,  fx9__effect__msl__uniform__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__uniform__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__constant__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Constant, type),
    &fx9__effect__msl__uniform_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Constant, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__constant__field_indices_by_name[] = {
  1,   /* field[1] = index */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange fx9__effect__msl__constant__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__constant__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Constant",
  "Constant",
  "Fx9__Effect__Msl__Constant",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Constant),
  2,
  fx9__effect__msl__constant__field_descriptors,
  fx9__effect__msl__constant__field_indices_by_name,
  1,  fx9__effect__msl__constant__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__constant__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__sampler__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Sampler, type),
    &fx9__effect__msl__sampler_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Sampler, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Sampler, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__sampler__field_indices_by_name[] = {
  1,   /* field[1] = index */
  2,   /* field[2] = name */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange fx9__effect__msl__sampler__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__sampler__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Sampler",
  "Sampler",
  "Fx9__Effect__Msl__Sampler",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Sampler),
  3,
  fx9__effect__msl__sampler__field_descriptors,
  fx9__effect__msl__sampler__field_indices_by_name,
  1,  fx9__effect__msl__sampler__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__sampler__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__attribute__field_descriptors[3] =
{
  {
    "usage",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Attribute, usage),
    &fx9__effect__msl__attribute_usage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Attribute, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Attribute, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__attribute__field_indices_by_name[] = {
  1,   /* field[1] = index */
  2,   /* field[2] = name */
  0,   /* field[0] = usage */
};
static const ProtobufCIntRange fx9__effect__msl__attribute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__attribute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Attribute",
  "Attribute",
  "Fx9__Effect__Msl__Attribute",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Attribute),
  3,
  fx9__effect__msl__attribute__field_descriptors,
  fx9__effect__msl__attribute__field_indices_by_name,
  1,  fx9__effect__msl__attribute__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__symbol__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Symbol, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_set",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Symbol, register_set),
    &fx9__effect__msl__register_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Symbol, register_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_count",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Symbol, register_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__symbol__field_indices_by_name[] = {
  0,   /* field[0] = name */
  3,   /* field[3] = register_count */
  2,   /* field[2] = register_index */
  1,   /* field[1] = register_set */
};
static const ProtobufCIntRange fx9__effect__msl__symbol__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__symbol__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Symbol",
  "Symbol",
  "Fx9__Effect__Msl__Symbol",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Symbol),
  4,
  fx9__effect__msl__symbol__field_descriptors,
  fx9__effect__msl__symbol__field_indices_by_name,
  1,  fx9__effect__msl__symbol__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__symbol__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__sampler_state__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__SamplerState, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__SamplerState, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__sampler_state__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange fx9__effect__msl__sampler_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__sampler_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.SamplerState",
  "SamplerState",
  "Fx9__Effect__Msl__SamplerState",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__SamplerState),
  2,
  fx9__effect__msl__sampler_state__field_descriptors,
  fx9__effect__msl__sampler_state__field_indices_by_name,
  1,  fx9__effect__msl__sampler_state__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__sampler_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__render_state__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__RenderState, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__RenderState, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__render_state__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange fx9__effect__msl__render_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__render_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.RenderState",
  "RenderState",
  "Fx9__Effect__Msl__RenderState",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__RenderState),
  2,
  fx9__effect__msl__render_state__field_descriptors,
  fx9__effect__msl__render_state__field_indices_by_name,
  1,  fx9__effect__msl__render_state__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__render_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__texture__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Texture, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampler_index",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Texture, sampler_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampler_states",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Texture, n_sampler_states),
    offsetof(Fx9__Effect__Msl__Texture, sampler_states),
    &fx9__effect__msl__sampler_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__texture__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = sampler_index */
  2,   /* field[2] = sampler_states */
};
static const ProtobufCIntRange fx9__effect__msl__texture__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__texture__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Texture",
  "Texture",
  "Fx9__Effect__Msl__Texture",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Texture),
  3,
  fx9__effect__msl__texture__field_descriptors,
  fx9__effect__msl__texture__field_indices_by_name,
  1,  fx9__effect__msl__texture__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__texture__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__shader__field_descriptors[11] =
{
  {
    "major_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Shader, major_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minor_version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Shader, minor_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_intructions",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Shader, num_intructions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Shader, type),
    &fx9__effect__msl__shader_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Shader, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uniforms",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Shader, n_uniforms),
    offsetof(Fx9__Effect__Msl__Shader, uniforms),
    &fx9__effect__msl__uniform__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "constants",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Shader, n_constants),
    offsetof(Fx9__Effect__Msl__Shader, constants),
    &fx9__effect__msl__constant__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "samplers",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Shader, n_samplers),
    offsetof(Fx9__Effect__Msl__Shader, samplers),
    &fx9__effect__msl__sampler__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Shader, n_attributes),
    offsetof(Fx9__Effect__Msl__Shader, attributes),
    &fx9__effect__msl__attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputs",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Shader, n_outputs),
    offsetof(Fx9__Effect__Msl__Shader, outputs),
    &fx9__effect__msl__attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbols",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Shader, n_symbols),
    offsetof(Fx9__Effect__Msl__Shader, symbols),
    &fx9__effect__msl__symbol__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__shader__field_indices_by_name[] = {
  8,   /* field[8] = attributes */
  4,   /* field[4] = code */
  6,   /* field[6] = constants */
  0,   /* field[0] = major_version */
  1,   /* field[1] = minor_version */
  2,   /* field[2] = num_intructions */
  9,   /* field[9] = outputs */
  7,   /* field[7] = samplers */
  10,   /* field[10] = symbols */
  3,   /* field[3] = type */
  5,   /* field[5] = uniforms */
};
static const ProtobufCIntRange fx9__effect__msl__shader__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__shader__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Shader",
  "Shader",
  "Fx9__Effect__Msl__Shader",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Shader),
  11,
  fx9__effect__msl__shader__field_descriptors,
  fx9__effect__msl__shader__field_indices_by_name,
  1,  fx9__effect__msl__shader__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__shader__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fx9__effect__msl__pass__field_descriptors[5] =
{
  {
    "vertex_shader",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Pass, vertex_shader),
    &fx9__effect__msl__shader__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_shader",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Fx9__Effect__Msl__Pass, pixel_shader),
    &fx9__effect__msl__shader__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "textures",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Pass, n_textures),
    offsetof(Fx9__Effect__Msl__Pass, textures),
    &fx9__effect__msl__texture__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "render_states",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Pass, n_render_states),
    offsetof(Fx9__Effect__Msl__Pass, render_states),
    &fx9__effect__msl__render_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertex_textures",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Fx9__Effect__Msl__Pass, n_vertex_textures),
    offsetof(Fx9__Effect__Msl__Pass, vertex_textures),
    &fx9__effect__msl__texture__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fx9__effect__msl__pass__field_indices_by_name[] = {
  1,   /* field[1] = pixel_shader */
  3,   /* field[3] = render_states */
  2,   /* field[2] = textures */
  0,   /* field[0] = vertex_shader */
  4,   /* field[4] = vertex_textures */
};
static const ProtobufCIntRange fx9__effect__msl__pass__number_ranges[2 + 1] =
{
  { 2, 0 },
  { 5, 2 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor fx9__effect__msl__pass__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.Pass",
  "Pass",
  "Fx9__Effect__Msl__Pass",
  "fx9.effect.msl",
  sizeof(Fx9__Effect__Msl__Pass),
  5,
  fx9__effect__msl__pass__field_descriptors,
  fx9__effect__msl__pass__field_indices_by_name,
  2,  fx9__effect__msl__pass__number_ranges,
  (ProtobufCMessageInit) fx9__effect__msl__pass__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue fx9__effect__msl__parameter_class__enum_values_by_number[6] =
{
  { "PC_SCALAR", "FX9__EFFECT__MSL__PARAMETER_CLASS__PC_SCALAR", 0 },
  { "PC_VECTOR", "FX9__EFFECT__MSL__PARAMETER_CLASS__PC_VECTOR", 1 },
  { "PC_MATRIX_ROWS", "FX9__EFFECT__MSL__PARAMETER_CLASS__PC_MATRIX_ROWS", 2 },
  { "PC_MATRIX_COLUMNS", "FX9__EFFECT__MSL__PARAMETER_CLASS__PC_MATRIX_COLUMNS", 3 },
  { "PC_OBJECT", "FX9__EFFECT__MSL__PARAMETER_CLASS__PC_OBJECT", 4 },
  { "PC_STRUCT", "FX9__EFFECT__MSL__PARAMETER_CLASS__PC_STRUCT", 5 },
};
static const ProtobufCIntRange fx9__effect__msl__parameter_class__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__parameter_class__enum_values_by_name[6] =
{
  { "PC_MATRIX_COLUMNS", 3 },
  { "PC_MATRIX_ROWS", 2 },
  { "PC_OBJECT", 4 },
  { "PC_SCALAR", 0 },
  { "PC_STRUCT", 5 },
  { "PC_VECTOR", 1 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__parameter_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.ParameterClass",
  "ParameterClass",
  "Fx9__Effect__Msl__ParameterClass",
  "fx9.effect.msl",
  6,
  fx9__effect__msl__parameter_class__enum_values_by_number,
  6,
  fx9__effect__msl__parameter_class__enum_values_by_name,
  1,
  fx9__effect__msl__parameter_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__msl__parameter_type__enum_values_by_number[20] =
{
  { "PT_VOID", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_VOID", 0 },
  { "PT_BOOL", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_BOOL", 1 },
  { "PT_INT", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_INT", 2 },
  { "PT_FLOAT", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_FLOAT", 3 },
  { "PT_STRING", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_STRING", 4 },
  { "PT_TEXTURE", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_TEXTURE", 5 },
  { "PT_TEXTURE1D", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_TEXTURE1D", 6 },
  { "PT_TEXTURE2D", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_TEXTURE2D", 7 },
  { "PT_TEXTURE3D", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_TEXTURE3D", 8 },
  { "PT_TEXTURECUBE", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_TEXTURECUBE", 9 },
  { "PT_SAMPLER", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_SAMPLER", 10 },
  { "PT_SAMPLER1D", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_SAMPLER1D", 11 },
  { "PT_SAMPLER2D", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_SAMPLER2D", 12 },
  { "PT_SAMPLER3D", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_SAMPLER3D", 13 },
  { "PT_SAMPLERCUBE", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_SAMPLERCUBE", 14 },
  { "PT_PIXELSHADER", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_PIXELSHADER", 15 },
  { "PT_VERTEXSHADER", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_VERTEXSHADER", 16 },
  { "PT_PIXELFRAGMENT", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_PIXELFRAGMENT", 17 },
  { "PT_VERTEXFRAGMENT", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_VERTEXFRAGMENT", 18 },
  { "PT_UNSUPPORTED", "FX9__EFFECT__MSL__PARAMETER_TYPE__PT_UNSUPPORTED", 19 },
};
static const ProtobufCIntRange fx9__effect__msl__parameter_type__value_ranges[] = {
{0, 0},{0, 20}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__parameter_type__enum_values_by_name[20] =
{
  { "PT_BOOL", 1 },
  { "PT_FLOAT", 3 },
  { "PT_INT", 2 },
  { "PT_PIXELFRAGMENT", 17 },
  { "PT_PIXELSHADER", 15 },
  { "PT_SAMPLER", 10 },
  { "PT_SAMPLER1D", 11 },
  { "PT_SAMPLER2D", 12 },
  { "PT_SAMPLER3D", 13 },
  { "PT_SAMPLERCUBE", 14 },
  { "PT_STRING", 4 },
  { "PT_TEXTURE", 5 },
  { "PT_TEXTURE1D", 6 },
  { "PT_TEXTURE2D", 7 },
  { "PT_TEXTURE3D", 8 },
  { "PT_TEXTURECUBE", 9 },
  { "PT_UNSUPPORTED", 19 },
  { "PT_VERTEXFRAGMENT", 18 },
  { "PT_VERTEXSHADER", 16 },
  { "PT_VOID", 0 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__parameter_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.ParameterType",
  "ParameterType",
  "Fx9__Effect__Msl__ParameterType",
  "fx9.effect.msl",
  20,
  fx9__effect__msl__parameter_type__enum_values_by_number,
  20,
  fx9__effect__msl__parameter_type__enum_values_by_name,
  1,
  fx9__effect__msl__parameter_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__msl__shader_type__enum_values_by_number[2] =
{
  { "ST_PIXEL", "FX9__EFFECT__MSL__SHADER_TYPE__ST_PIXEL", 1 },
  { "ST_VERTEX", "FX9__EFFECT__MSL__SHADER_TYPE__ST_VERTEX", 2 },
};
static const ProtobufCIntRange fx9__effect__msl__shader_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__shader_type__enum_values_by_name[2] =
{
  { "ST_PIXEL", 0 },
  { "ST_VERTEX", 1 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__shader_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.ShaderType",
  "ShaderType",
  "Fx9__Effect__Msl__ShaderType",
  "fx9.effect.msl",
  2,
  fx9__effect__msl__shader_type__enum_values_by_number,
  2,
  fx9__effect__msl__shader_type__enum_values_by_name,
  1,
  fx9__effect__msl__shader_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__msl__uniform_type__enum_values_by_number[3] =
{
  { "UT_FLOAT", "FX9__EFFECT__MSL__UNIFORM_TYPE__UT_FLOAT", 0 },
  { "UT_INT", "FX9__EFFECT__MSL__UNIFORM_TYPE__UT_INT", 1 },
  { "UT_BOOL", "FX9__EFFECT__MSL__UNIFORM_TYPE__UT_BOOL", 2 },
};
static const ProtobufCIntRange fx9__effect__msl__uniform_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__uniform_type__enum_values_by_name[3] =
{
  { "UT_BOOL", 2 },
  { "UT_FLOAT", 0 },
  { "UT_INT", 1 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__uniform_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.UniformType",
  "UniformType",
  "Fx9__Effect__Msl__UniformType",
  "fx9.effect.msl",
  3,
  fx9__effect__msl__uniform_type__enum_values_by_number,
  3,
  fx9__effect__msl__uniform_type__enum_values_by_name,
  1,
  fx9__effect__msl__uniform_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__msl__sampler_type__enum_values_by_number[3] =
{
  { "SAMPLER_2D", "FX9__EFFECT__MSL__SAMPLER_TYPE__SAMPLER_2D", 0 },
  { "SAMPLER_CUBE", "FX9__EFFECT__MSL__SAMPLER_TYPE__SAMPLER_CUBE", 1 },
  { "SAMPLER_VOLUME", "FX9__EFFECT__MSL__SAMPLER_TYPE__SAMPLER_VOLUME", 2 },
};
static const ProtobufCIntRange fx9__effect__msl__sampler_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__sampler_type__enum_values_by_name[3] =
{
  { "SAMPLER_2D", 0 },
  { "SAMPLER_CUBE", 1 },
  { "SAMPLER_VOLUME", 2 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__sampler_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.SamplerType",
  "SamplerType",
  "Fx9__Effect__Msl__SamplerType",
  "fx9.effect.msl",
  3,
  fx9__effect__msl__sampler_type__enum_values_by_number,
  3,
  fx9__effect__msl__sampler_type__enum_values_by_name,
  1,
  fx9__effect__msl__sampler_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__msl__attribute_usage__enum_values_by_number[14] =
{
  { "AU_POSITION", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_POSITION", 0 },
  { "AU_BLENDWEIGHT", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_BLENDWEIGHT", 1 },
  { "AU_BLENDINDICES", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_BLENDINDICES", 2 },
  { "AU_NORMAL", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_NORMAL", 3 },
  { "AU_POINTSIZE", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_POINTSIZE", 4 },
  { "AU_TEXCOORD", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_TEXCOORD", 5 },
  { "AU_TANGENT", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_TANGENT", 6 },
  { "AU_BINORMAL", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_BINORMAL", 7 },
  { "AU_TESSFACTOR", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_TESSFACTOR", 8 },
  { "AU_POSITIONT", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_POSITIONT", 9 },
  { "AU_COLOR", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_COLOR", 10 },
  { "AU_FOG", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_FOG", 11 },
  { "AU_DEPTH", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_DEPTH", 12 },
  { "AU_SAMPLE", "FX9__EFFECT__MSL__ATTRIBUTE_USAGE__AU_SAMPLE", 13 },
};
static const ProtobufCIntRange fx9__effect__msl__attribute_usage__value_ranges[] = {
{0, 0},{0, 14}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__attribute_usage__enum_values_by_name[14] =
{
  { "AU_BINORMAL", 7 },
  { "AU_BLENDINDICES", 2 },
  { "AU_BLENDWEIGHT", 1 },
  { "AU_COLOR", 10 },
  { "AU_DEPTH", 12 },
  { "AU_FOG", 11 },
  { "AU_NORMAL", 3 },
  { "AU_POINTSIZE", 4 },
  { "AU_POSITION", 0 },
  { "AU_POSITIONT", 9 },
  { "AU_SAMPLE", 13 },
  { "AU_TANGENT", 6 },
  { "AU_TESSFACTOR", 8 },
  { "AU_TEXCOORD", 5 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__attribute_usage__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.AttributeUsage",
  "AttributeUsage",
  "Fx9__Effect__Msl__AttributeUsage",
  "fx9.effect.msl",
  14,
  fx9__effect__msl__attribute_usage__enum_values_by_number,
  14,
  fx9__effect__msl__attribute_usage__enum_values_by_name,
  1,
  fx9__effect__msl__attribute_usage__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue fx9__effect__msl__register_set__enum_values_by_number[4] =
{
  { "RS_BOOL", "FX9__EFFECT__MSL__REGISTER_SET__RS_BOOL", 0 },
  { "RS_INT4", "FX9__EFFECT__MSL__REGISTER_SET__RS_INT4", 1 },
  { "RS_FLOAT4", "FX9__EFFECT__MSL__REGISTER_SET__RS_FLOAT4", 2 },
  { "RS_SAMPLER", "FX9__EFFECT__MSL__REGISTER_SET__RS_SAMPLER", 3 },
};
static const ProtobufCIntRange fx9__effect__msl__register_set__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex fx9__effect__msl__register_set__enum_values_by_name[4] =
{
  { "RS_BOOL", 0 },
  { "RS_FLOAT4", 2 },
  { "RS_INT4", 1 },
  { "RS_SAMPLER", 3 },
};
const ProtobufCEnumDescriptor fx9__effect__msl__register_set__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "fx9.effect.msl.RegisterSet",
  "RegisterSet",
  "Fx9__Effect__Msl__RegisterSet",
  "fx9.effect.msl",
  4,
  fx9__effect__msl__register_set__enum_values_by_number,
  4,
  fx9__effect__msl__register_set__enum_values_by_name,
  1,
  fx9__effect__msl__register_set__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
