/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: plugin.proto */

#ifndef PROTOBUF_C_plugin_2eproto__INCLUDED
#define PROTOBUF_C_plugin_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "common.pb-c.h"

typedef struct _Nanoem__Application__Plugin__AudioDescription Nanoem__Application__Plugin__AudioDescription;
typedef struct _Nanoem__Application__Plugin__CameraDescription Nanoem__Application__Plugin__CameraDescription;
typedef struct _Nanoem__Application__Plugin__LightDescription Nanoem__Application__Plugin__LightDescription;
typedef struct _Nanoem__Application__Plugin__UIComponent Nanoem__Application__Plugin__UIComponent;
typedef struct _Nanoem__Application__Plugin__UIComponent__Label Nanoem__Application__Plugin__UIComponent__Label;
typedef struct _Nanoem__Application__Plugin__UIComponent__Selectable Nanoem__Application__Plugin__UIComponent__Selectable;
typedef struct _Nanoem__Application__Plugin__UIComponent__Button Nanoem__Application__Plugin__UIComponent__Button;
typedef struct _Nanoem__Application__Plugin__UIComponent__CheckBox Nanoem__Application__Plugin__UIComponent__CheckBox;
typedef struct _Nanoem__Application__Plugin__UIComponent__RadioButton Nanoem__Application__Plugin__UIComponent__RadioButton;
typedef struct _Nanoem__Application__Plugin__UIComponent__ComboBox Nanoem__Application__Plugin__UIComponent__ComboBox;
typedef struct _Nanoem__Application__Plugin__UIComponent__DragScalarN Nanoem__Application__Plugin__UIComponent__DragScalarN;
typedef struct _Nanoem__Application__Plugin__UIComponent__SliderScalarN Nanoem__Application__Plugin__UIComponent__SliderScalarN;
typedef struct _Nanoem__Application__Plugin__UIComponent__InputScalarN Nanoem__Application__Plugin__UIComponent__InputScalarN;
typedef struct _Nanoem__Application__Plugin__UIComponent__Separator Nanoem__Application__Plugin__UIComponent__Separator;
typedef struct _Nanoem__Application__Plugin__UIComponent__SameLine Nanoem__Application__Plugin__UIComponent__SameLine;
typedef struct _Nanoem__Application__Plugin__UIComponent__ChildWindow Nanoem__Application__Plugin__UIComponent__ChildWindow;
typedef struct _Nanoem__Application__Plugin__UIComponent__Dummy Nanoem__Application__Plugin__UIComponent__Dummy;
typedef struct _Nanoem__Application__Plugin__UIComponent__Tree Nanoem__Application__Plugin__UIComponent__Tree;
typedef struct _Nanoem__Application__Plugin__UIComponent__Canvas Nanoem__Application__Plugin__UIComponent__Canvas;
typedef struct _Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand;
typedef struct _Nanoem__Application__Plugin__UIWindow Nanoem__Application__Plugin__UIWindow;


/* --- enums --- */

typedef enum _Nanoem__Application__Plugin__UIComponent__DataType {
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S8 = 1,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__U8 = 2,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S16 = 3,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__U16 = 4,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S32 = 5,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__U32 = 6,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S64 = 7,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__U64 = 8,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__FLOAT = 9,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__DOUBLE = 10
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE)
} Nanoem__Application__Plugin__UIComponent__DataType;

/* --- messages --- */

struct  _Nanoem__Application__Plugin__AudioDescription
{
  ProtobufCMessage base;
  uint32_t bits_per_sample;
  uint32_t num_channels;
  uint32_t sample_rate;
  float volume_gain;
  Nanoem__Common__Rational *current_offset;
  Nanoem__Common__Rational *duration;
};
#define NANOEM__APPLICATION__PLUGIN__AUDIO_DESCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__audio_description__descriptor) \
    , 0, 0, 0, 0, NULL, NULL }


struct  _Nanoem__Application__Plugin__CameraDescription
{
  ProtobufCMessage base;
  Nanoem__Common__Vector4 *look_at;
  Nanoem__Common__Vector4 *angle;
  float distance;
  float fov;
  protobuf_c_boolean is_perspective;
};
#define NANOEM__APPLICATION__PLUGIN__CAMERA_DESCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__camera_description__descriptor) \
    , NULL, NULL, 0, 0, 0 }


struct  _Nanoem__Application__Plugin__LightDescription
{
  ProtobufCMessage base;
  Nanoem__Common__Vector4 *color;
  Nanoem__Common__Vector4 *direction;
};
#define NANOEM__APPLICATION__PLUGIN__LIGHT_DESCRIPTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__light_description__descriptor) \
    , NULL, NULL }


struct  _Nanoem__Application__Plugin__UIComponent__Label
{
  ProtobufCMessage base;
  char *text;
  protobuf_c_boolean has_color;
  uint32_t color;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__LABEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__label__descriptor) \
    , NULL, 0, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__Selectable
{
  ProtobufCMessage base;
  char *id;
  char *text;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__SELECTABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__selectable__descriptor) \
    , NULL, NULL }


struct  _Nanoem__Application__Plugin__UIComponent__Button
{
  ProtobufCMessage base;
  char *id;
  char *text;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__BUTTON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__button__descriptor) \
    , NULL, NULL }


struct  _Nanoem__Application__Plugin__UIComponent__CheckBox
{
  ProtobufCMessage base;
  char *id;
  char *text;
  protobuf_c_boolean value;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__CHECK_BOX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__check_box__descriptor) \
    , NULL, NULL, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__RadioButton
{
  ProtobufCMessage base;
  char *id;
  char *text;
  protobuf_c_boolean active;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__RADIO_BUTTON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__radio_button__descriptor) \
    , NULL, NULL, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__ComboBox
{
  ProtobufCMessage base;
  char *id;
  char *text;
  uint32_t selected_index;
  size_t n_selectables;
  Nanoem__Application__Plugin__UIComponent__Selectable **selectables;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__COMBO_BOX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__combo_box__descriptor) \
    , NULL, NULL, 0, 0,NULL }


struct  _Nanoem__Application__Plugin__UIComponent__DragScalarN
{
  ProtobufCMessage base;
  Nanoem__Application__Plugin__UIComponent__DataType data_type;
  int32_t num_components;
  float speed;
  char *id;
  char *text;
  ProtobufCBinaryData value;
  protobuf_c_boolean has_power;
  float power;
  protobuf_c_boolean has_min;
  ProtobufCBinaryData min;
  protobuf_c_boolean has_max;
  ProtobufCBinaryData max;
  char *format;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DRAG_SCALAR_N__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__drag_scalar_n__descriptor) \
    , NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S8, 0, 0, NULL, NULL, {0,NULL}, 0, 0, 0, {0,NULL}, 0, {0,NULL}, NULL }


struct  _Nanoem__Application__Plugin__UIComponent__SliderScalarN
{
  ProtobufCMessage base;
  Nanoem__Application__Plugin__UIComponent__DataType data_type;
  int32_t num_components;
  char *id;
  char *text;
  ProtobufCBinaryData value;
  protobuf_c_boolean has_min;
  ProtobufCBinaryData min;
  protobuf_c_boolean has_max;
  ProtobufCBinaryData max;
  char *format;
  protobuf_c_boolean has_power;
  float power;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__SLIDER_SCALAR_N__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__slider_scalar_n__descriptor) \
    , NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S8, 0, NULL, NULL, {0,NULL}, 0, {0,NULL}, 0, {0,NULL}, NULL, 0, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__InputScalarN
{
  ProtobufCMessage base;
  Nanoem__Application__Plugin__UIComponent__DataType data_type;
  int32_t num_components;
  char *id;
  char *text;
  ProtobufCBinaryData value;
  protobuf_c_boolean has_step;
  ProtobufCBinaryData step;
  protobuf_c_boolean has_step_fast;
  ProtobufCBinaryData step_fast;
  char *format;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__INPUT_SCALAR_N__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__input_scalar_n__descriptor) \
    , NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DATA_TYPE__S8, 0, NULL, NULL, {0,NULL}, 0, {0,NULL}, 0, {0,NULL}, NULL }


struct  _Nanoem__Application__Plugin__UIComponent__Separator
{
  ProtobufCMessage base;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__SEPARATOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__separator__descriptor) \
     }


struct  _Nanoem__Application__Plugin__UIComponent__SameLine
{
  ProtobufCMessage base;
  protobuf_c_boolean has_offset_from_start_x;
  float offset_from_start_x;
  protobuf_c_boolean has_spacing_w;
  float spacing_w;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__SAME_LINE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__same_line__descriptor) \
    , 0, 0, 0, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__ChildWindow
{
  ProtobufCMessage base;
  char *id;
  size_t n_components;
  Nanoem__Application__Plugin__UIComponent **components;
  protobuf_c_boolean has_width;
  float width;
  protobuf_c_boolean has_height;
  float height;
  protobuf_c_boolean has_border;
  protobuf_c_boolean border;
  protobuf_c_boolean has_flags;
  uint32_t flags;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__CHILD_WINDOW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__child_window__descriptor) \
    , NULL, 0,NULL, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__Dummy
{
  ProtobufCMessage base;
  protobuf_c_boolean has_width;
  float width;
  protobuf_c_boolean has_height;
  float height;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__DUMMY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__dummy__descriptor) \
    , 0, 0, 0, 0 }


struct  _Nanoem__Application__Plugin__UIComponent__Tree
{
  ProtobufCMessage base;
  char *id;
  size_t n_components;
  Nanoem__Application__Plugin__UIComponent **components;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TREE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__tree__descriptor) \
    , NULL, 0,NULL }


struct  _Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand
{
  ProtobufCMessage base;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__CANVAS__DRAW_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__canvas__draw_command__descriptor) \
     }


struct  _Nanoem__Application__Plugin__UIComponent__Canvas
{
  ProtobufCMessage base;
  size_t n_commands;
  Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand **commands;
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__CANVAS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__canvas__descriptor) \
    , 0,NULL }


typedef enum {
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE__NOT_SET = 0,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_SEPARATOR = 1,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_LABEL = 2,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_BUTTON = 3,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_CHECK_BOX = 4,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_RADIO_BUTTON = 5,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_SELECTABLE = 6,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_COMBO_BOX = 7,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_DRAG_SCALAR_N = 8,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_SLIDER_SCALAR_N = 9,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_INPUT_SCALAR_N = 10,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_SAME_LINE = 11,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_CHILD_WINDOW = 12,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_DUMMY = 13,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_TREE = 14,
  NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE_CANVAS = 15
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE)
} Nanoem__Application__Plugin__UIComponent__TypeCase;

struct  _Nanoem__Application__Plugin__UIComponent
{
  ProtobufCMessage base;
  Nanoem__Application__Plugin__UIComponent__TypeCase type_case;
  union {
    Nanoem__Application__Plugin__UIComponent__Separator *separator;
    Nanoem__Application__Plugin__UIComponent__Label *label;
    Nanoem__Application__Plugin__UIComponent__Button *button;
    Nanoem__Application__Plugin__UIComponent__CheckBox *check_box;
    Nanoem__Application__Plugin__UIComponent__RadioButton *radio_button;
    Nanoem__Application__Plugin__UIComponent__Selectable *selectable;
    Nanoem__Application__Plugin__UIComponent__ComboBox *combo_box;
    Nanoem__Application__Plugin__UIComponent__DragScalarN *drag_scalar_n;
    Nanoem__Application__Plugin__UIComponent__SliderScalarN *slider_scalar_n;
    Nanoem__Application__Plugin__UIComponent__InputScalarN *input_scalar_n;
    Nanoem__Application__Plugin__UIComponent__SameLine *same_line;
    Nanoem__Application__Plugin__UIComponent__ChildWindow *child_window;
    Nanoem__Application__Plugin__UIComponent__Dummy *dummy;
    Nanoem__Application__Plugin__UIComponent__Tree *tree;
    Nanoem__Application__Plugin__UIComponent__Canvas *canvas;
  };
};
#define NANOEM__APPLICATION__PLUGIN__UICOMPONENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uicomponent__descriptor) \
    , NANOEM__APPLICATION__PLUGIN__UICOMPONENT__TYPE__NOT_SET, {0} }


struct  _Nanoem__Application__Plugin__UIWindow
{
  ProtobufCMessage base;
  char *id;
  char *title;
  size_t n_items;
  Nanoem__Application__Plugin__UIComponent **items;
};
#define NANOEM__APPLICATION__PLUGIN__UIWINDOW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__application__plugin__uiwindow__descriptor) \
    , NULL, NULL, 0,NULL }


/* Nanoem__Application__Plugin__AudioDescription methods */
void   nanoem__application__plugin__audio_description__init
                     (Nanoem__Application__Plugin__AudioDescription         *message);
size_t nanoem__application__plugin__audio_description__get_packed_size
                     (const Nanoem__Application__Plugin__AudioDescription   *message);
size_t nanoem__application__plugin__audio_description__pack
                     (const Nanoem__Application__Plugin__AudioDescription   *message,
                      uint8_t             *out);
size_t nanoem__application__plugin__audio_description__pack_to_buffer
                     (const Nanoem__Application__Plugin__AudioDescription   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Application__Plugin__AudioDescription *
       nanoem__application__plugin__audio_description__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__application__plugin__audio_description__free_unpacked
                     (Nanoem__Application__Plugin__AudioDescription *message,
                      ProtobufCAllocator *allocator);
/* Nanoem__Application__Plugin__CameraDescription methods */
void   nanoem__application__plugin__camera_description__init
                     (Nanoem__Application__Plugin__CameraDescription         *message);
size_t nanoem__application__plugin__camera_description__get_packed_size
                     (const Nanoem__Application__Plugin__CameraDescription   *message);
size_t nanoem__application__plugin__camera_description__pack
                     (const Nanoem__Application__Plugin__CameraDescription   *message,
                      uint8_t             *out);
size_t nanoem__application__plugin__camera_description__pack_to_buffer
                     (const Nanoem__Application__Plugin__CameraDescription   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Application__Plugin__CameraDescription *
       nanoem__application__plugin__camera_description__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__application__plugin__camera_description__free_unpacked
                     (Nanoem__Application__Plugin__CameraDescription *message,
                      ProtobufCAllocator *allocator);
/* Nanoem__Application__Plugin__LightDescription methods */
void   nanoem__application__plugin__light_description__init
                     (Nanoem__Application__Plugin__LightDescription         *message);
size_t nanoem__application__plugin__light_description__get_packed_size
                     (const Nanoem__Application__Plugin__LightDescription   *message);
size_t nanoem__application__plugin__light_description__pack
                     (const Nanoem__Application__Plugin__LightDescription   *message,
                      uint8_t             *out);
size_t nanoem__application__plugin__light_description__pack_to_buffer
                     (const Nanoem__Application__Plugin__LightDescription   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Application__Plugin__LightDescription *
       nanoem__application__plugin__light_description__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__application__plugin__light_description__free_unpacked
                     (Nanoem__Application__Plugin__LightDescription *message,
                      ProtobufCAllocator *allocator);
/* Nanoem__Application__Plugin__UIComponent__Label methods */
void   nanoem__application__plugin__uicomponent__label__init
                     (Nanoem__Application__Plugin__UIComponent__Label         *message);
/* Nanoem__Application__Plugin__UIComponent__Selectable methods */
void   nanoem__application__plugin__uicomponent__selectable__init
                     (Nanoem__Application__Plugin__UIComponent__Selectable         *message);
/* Nanoem__Application__Plugin__UIComponent__Button methods */
void   nanoem__application__plugin__uicomponent__button__init
                     (Nanoem__Application__Plugin__UIComponent__Button         *message);
/* Nanoem__Application__Plugin__UIComponent__CheckBox methods */
void   nanoem__application__plugin__uicomponent__check_box__init
                     (Nanoem__Application__Plugin__UIComponent__CheckBox         *message);
/* Nanoem__Application__Plugin__UIComponent__RadioButton methods */
void   nanoem__application__plugin__uicomponent__radio_button__init
                     (Nanoem__Application__Plugin__UIComponent__RadioButton         *message);
/* Nanoem__Application__Plugin__UIComponent__ComboBox methods */
void   nanoem__application__plugin__uicomponent__combo_box__init
                     (Nanoem__Application__Plugin__UIComponent__ComboBox         *message);
/* Nanoem__Application__Plugin__UIComponent__DragScalarN methods */
void   nanoem__application__plugin__uicomponent__drag_scalar_n__init
                     (Nanoem__Application__Plugin__UIComponent__DragScalarN         *message);
/* Nanoem__Application__Plugin__UIComponent__SliderScalarN methods */
void   nanoem__application__plugin__uicomponent__slider_scalar_n__init
                     (Nanoem__Application__Plugin__UIComponent__SliderScalarN         *message);
/* Nanoem__Application__Plugin__UIComponent__InputScalarN methods */
void   nanoem__application__plugin__uicomponent__input_scalar_n__init
                     (Nanoem__Application__Plugin__UIComponent__InputScalarN         *message);
/* Nanoem__Application__Plugin__UIComponent__Separator methods */
void   nanoem__application__plugin__uicomponent__separator__init
                     (Nanoem__Application__Plugin__UIComponent__Separator         *message);
/* Nanoem__Application__Plugin__UIComponent__SameLine methods */
void   nanoem__application__plugin__uicomponent__same_line__init
                     (Nanoem__Application__Plugin__UIComponent__SameLine         *message);
/* Nanoem__Application__Plugin__UIComponent__ChildWindow methods */
void   nanoem__application__plugin__uicomponent__child_window__init
                     (Nanoem__Application__Plugin__UIComponent__ChildWindow         *message);
/* Nanoem__Application__Plugin__UIComponent__Dummy methods */
void   nanoem__application__plugin__uicomponent__dummy__init
                     (Nanoem__Application__Plugin__UIComponent__Dummy         *message);
/* Nanoem__Application__Plugin__UIComponent__Tree methods */
void   nanoem__application__plugin__uicomponent__tree__init
                     (Nanoem__Application__Plugin__UIComponent__Tree         *message);
/* Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand methods */
void   nanoem__application__plugin__uicomponent__canvas__draw_command__init
                     (Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand         *message);
/* Nanoem__Application__Plugin__UIComponent__Canvas methods */
void   nanoem__application__plugin__uicomponent__canvas__init
                     (Nanoem__Application__Plugin__UIComponent__Canvas         *message);
/* Nanoem__Application__Plugin__UIComponent methods */
void   nanoem__application__plugin__uicomponent__init
                     (Nanoem__Application__Plugin__UIComponent         *message);
size_t nanoem__application__plugin__uicomponent__get_packed_size
                     (const Nanoem__Application__Plugin__UIComponent   *message);
size_t nanoem__application__plugin__uicomponent__pack
                     (const Nanoem__Application__Plugin__UIComponent   *message,
                      uint8_t             *out);
size_t nanoem__application__plugin__uicomponent__pack_to_buffer
                     (const Nanoem__Application__Plugin__UIComponent   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Application__Plugin__UIComponent *
       nanoem__application__plugin__uicomponent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__application__plugin__uicomponent__free_unpacked
                     (Nanoem__Application__Plugin__UIComponent *message,
                      ProtobufCAllocator *allocator);
/* Nanoem__Application__Plugin__UIWindow methods */
void   nanoem__application__plugin__uiwindow__init
                     (Nanoem__Application__Plugin__UIWindow         *message);
size_t nanoem__application__plugin__uiwindow__get_packed_size
                     (const Nanoem__Application__Plugin__UIWindow   *message);
size_t nanoem__application__plugin__uiwindow__pack
                     (const Nanoem__Application__Plugin__UIWindow   *message,
                      uint8_t             *out);
size_t nanoem__application__plugin__uiwindow__pack_to_buffer
                     (const Nanoem__Application__Plugin__UIWindow   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Application__Plugin__UIWindow *
       nanoem__application__plugin__uiwindow__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__application__plugin__uiwindow__free_unpacked
                     (Nanoem__Application__Plugin__UIWindow *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Nanoem__Application__Plugin__AudioDescription_Closure)
                 (const Nanoem__Application__Plugin__AudioDescription *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__CameraDescription_Closure)
                 (const Nanoem__Application__Plugin__CameraDescription *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__LightDescription_Closure)
                 (const Nanoem__Application__Plugin__LightDescription *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Label_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Label *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Selectable_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Selectable *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Button_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Button *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__CheckBox_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__CheckBox *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__RadioButton_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__RadioButton *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__ComboBox_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__ComboBox *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__DragScalarN_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__DragScalarN *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__SliderScalarN_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__SliderScalarN *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__InputScalarN_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__InputScalarN *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Separator_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Separator *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__SameLine_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__SameLine *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__ChildWindow_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__ChildWindow *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Dummy_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Dummy *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Tree_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Tree *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Canvas__DrawCommand *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent__Canvas_Closure)
                 (const Nanoem__Application__Plugin__UIComponent__Canvas *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIComponent_Closure)
                 (const Nanoem__Application__Plugin__UIComponent *message,
                  void *closure_data);
typedef void (*Nanoem__Application__Plugin__UIWindow_Closure)
                 (const Nanoem__Application__Plugin__UIWindow *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor nanoem__application__plugin__audio_description__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__camera_description__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__light_description__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__label__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__selectable__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__button__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__check_box__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__radio_button__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__combo_box__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__drag_scalar_n__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__slider_scalar_n__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__input_scalar_n__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__separator__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__same_line__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__child_window__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__dummy__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__tree__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__canvas__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uicomponent__canvas__draw_command__descriptor;
extern const ProtobufCEnumDescriptor    nanoem__application__plugin__uicomponent__data_type__descriptor;
extern const ProtobufCMessageDescriptor nanoem__application__plugin__uiwindow__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_plugin_2eproto__INCLUDED */
