/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: translation.proto */

#ifndef PROTOBUF_C_translation_2eproto__INCLUDED
#define PROTOBUF_C_translation_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "common.pb-c.h"

typedef struct Nanoem__Translation__Phrase Nanoem__Translation__Phrase;
typedef struct Nanoem__Translation__Unit Nanoem__Translation__Unit;
typedef struct Nanoem__Translation__Bundle Nanoem__Translation__Bundle;


/* --- enums --- */


/* --- messages --- */

struct  Nanoem__Translation__Phrase
{
  ProtobufCMessage base;
  char *id;
  char *text;
};
#define NANOEM__TRANSLATION__PHRASE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__translation__phrase__descriptor) \
    , NULL, NULL }


struct  Nanoem__Translation__Unit
{
  ProtobufCMessage base;
  Nanoem__Common__Language language;
  size_t n_phrases;
  Nanoem__Translation__Phrase **phrases;
};
#define NANOEM__TRANSLATION__UNIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__translation__unit__descriptor) \
    , NANOEM__COMMON__LANGUAGE__LC_UNKNOWN, 0,NULL }


struct  Nanoem__Translation__Bundle
{
  ProtobufCMessage base;
  size_t n_units;
  Nanoem__Translation__Unit **units;
};
#define NANOEM__TRANSLATION__BUNDLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&nanoem__translation__bundle__descriptor) \
    , 0,NULL }


/* Nanoem__Translation__Phrase methods */
void   nanoem__translation__phrase__init
                     (Nanoem__Translation__Phrase         *message);
size_t nanoem__translation__phrase__get_packed_size
                     (const Nanoem__Translation__Phrase   *message);
size_t nanoem__translation__phrase__pack
                     (const Nanoem__Translation__Phrase   *message,
                      uint8_t             *out);
size_t nanoem__translation__phrase__pack_to_buffer
                     (const Nanoem__Translation__Phrase   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Translation__Phrase *
       nanoem__translation__phrase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__translation__phrase__free_unpacked
                     (Nanoem__Translation__Phrase *message,
                      ProtobufCAllocator *allocator);
/* Nanoem__Translation__Unit methods */
void   nanoem__translation__unit__init
                     (Nanoem__Translation__Unit         *message);
size_t nanoem__translation__unit__get_packed_size
                     (const Nanoem__Translation__Unit   *message);
size_t nanoem__translation__unit__pack
                     (const Nanoem__Translation__Unit   *message,
                      uint8_t             *out);
size_t nanoem__translation__unit__pack_to_buffer
                     (const Nanoem__Translation__Unit   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Translation__Unit *
       nanoem__translation__unit__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__translation__unit__free_unpacked
                     (Nanoem__Translation__Unit *message,
                      ProtobufCAllocator *allocator);
/* Nanoem__Translation__Bundle methods */
void   nanoem__translation__bundle__init
                     (Nanoem__Translation__Bundle         *message);
size_t nanoem__translation__bundle__get_packed_size
                     (const Nanoem__Translation__Bundle   *message);
size_t nanoem__translation__bundle__pack
                     (const Nanoem__Translation__Bundle   *message,
                      uint8_t             *out);
size_t nanoem__translation__bundle__pack_to_buffer
                     (const Nanoem__Translation__Bundle   *message,
                      ProtobufCBuffer     *buffer);
Nanoem__Translation__Bundle *
       nanoem__translation__bundle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   nanoem__translation__bundle__free_unpacked
                     (Nanoem__Translation__Bundle *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Nanoem__Translation__Phrase_Closure)
                 (const Nanoem__Translation__Phrase *message,
                  void *closure_data);
typedef void (*Nanoem__Translation__Unit_Closure)
                 (const Nanoem__Translation__Unit *message,
                  void *closure_data);
typedef void (*Nanoem__Translation__Bundle_Closure)
                 (const Nanoem__Translation__Bundle *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor nanoem__translation__phrase__descriptor;
extern const ProtobufCMessageDescriptor nanoem__translation__unit__descriptor;
extern const ProtobufCMessageDescriptor nanoem__translation__bundle__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_translation_2eproto__INCLUDED */
