[package]
name = "plugin_wasm_test_model_full"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
libc.workspace = true
