/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION 1179
#define MOJOSHADER_CHANGESET "hg-1179:6dd73a80629b"
#endif

