[package]
name = "plugin_wasm_test_motion_minimum"
version = "0.1.0"
authors = ["hkrn <129939+hkrn@users.noreply.github.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
libc = "0.2"
